.gitignore
Please, MB, check if pycharm-related files are correctly ignored now
=> Fix gitignore, as needed after moving svir to the main folder in the new repo

svir.py, ui/ui_upload_metadata.py, ui/ui_upload_metadata.ui, upload_metadata_dialog.py
add a button that closes the uploader and shows the layer in the default system webbrowser
=> add close and show in browser button

import_sv_data.py
See https://bugs.launchpad.net/oq-svir/+bug/1414711 and the Platform-side companion PR https://github.com/gem/oq-platform/pull/363
=> Use POST request to export socioeconomic data from the platform

svir.py
This PR substitutes https://github.com/gem/oq-svir-qgis/pull/23 (see the description there)
=> After styling the layer, reset the default symbol

settings_dialog.py, shared.py, ui/ui_settings.py, ui/ui_settings.ui
=> Add a link to the OQ-Platform registration to the dialog setting connection settings to the platform

download_layer_dialog.py, ui/ui_download_layer.py, ui/ui_download_layer.ui
Otherwise, if the list is huge, it becomes very uncomfortable.
The GUI is also slightly improved to display the layer's info more clearly
=> Use QListWidget instead of QCombobox to list the available layers on the OQ-Platform

import_sv_data.py, svir.py
This PR takes advantage of https://github.com/gem/oq-platform/pull/403 to stream the socioeconomic data downloaded from the Platform.
I am still having problems attempting to display the progress bar properly. Perhaps this will be solved as soon as the downloading will be performed in a separate thread.
=> Stream the socioeconomic data downloaded from the platform and display a progress bar

projects_manager_dialog.py
=> When setting the project definition's title in the project manager, also update the text in the combobox

svir.py, utils.py
This PR fixes a bug in a function used to update the project definitions in order to track a new transformed field.
=> Fix the replace_fields function

oq_irmt/Makefile, oq_irmt/dialogs/attribute_selection_dialog.py, oq_irmt/dialogs/download_layer_dialog.py, oq_irmt/dialogs/select_input_layers_dialog.py, oq_irmt/dialogs/upload_settings_dialog.py, oq_irmt/irmt.py, oq_irmt/utilities/utils.py
moving the accept logic into the dialog
=> Refactoring dialogs

svir/metadata.txt, svir/ui/tool_button_with_help_link.py
=> Fix "What's This?" functionality on Windows

svir/dialogs/projects_manager_dialog.py, svir/irmt.py, svir/metadata.txt
Fix https://github.com/gem/oq-irmt-qgis/issues/121
=> Enable 'Project definitions manager' for new projects that are not yet associated to any project definition

svir/dialogs/upload_settings_dialog.py
suggesting to use the Project Definition Manager in case of duplication.
Only partially addressing https://github.com/gem/oq-irmt-qgis/issues/130
=> Fix updating project title

svir/thread_worker/upload_worker.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/132
=> First attempt to update the projection before uploading to platform

svir/recovery_modeling/recovery_modeling.py
=> Added support for minimum number of samples

svir/dialogs/upload_settings_dialog.py, svir/metadata.txt
Companion of https://github.com/gem/oq-platform/pull/616
=> Add CC4 licenses

svir/dialogs/load_csv_as_layer_dialog.py, svir/dialogs/load_geojson_as_layer_dialog.py, svir/dialogs/load_npz_as_layer_dialog.py, svir/dialogs/settings_dialog.py, svir/irmt.py, svir/ui/ui_settings.ui, svir/utilities/utils.py
This was done by @mbernasocchi 
I prefer to keep it separated from another new feature that makes possible to enable/disable automatic re-styling at each re-calculation of composite indices.
=> Configurable styles

svir/dialogs/settings_dialog.py, svir/utilities/utils.py
=> Use readBoolEntry for QgsProject setting instead of the generic readEntry

svir/ui/ui_settings.ui
Fixes https://github.com/gem/oq-irmt-qgis/issues/185
=> Place each setting inside the corresponding groupBox

svir/dialogs/recovery_modeling_dialog.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/188
=> Fix a wrong layer pre-selection in a dropdown menu for recovery modeling

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_csv_as_layer_dialog.py, svir/dialogs/load_geojson_as_layer_dialog.py, svir/dialogs/load_npz_as_layer_dialog.py, svir/dialogs/settings_dialog.py, svir/irmt.py, svir/metadata.txt, svir/utilities/utils.py
I am adding warnings in 2 cases:
1. asking confirmation before removing an OQ-Engine calculation (fixes https://github.com/gem/oq-irmt-qgis/issues/200)
2. notifying that a stored color setting was corrupted and the default value was restored instead (fixes https://github.com/gem/oq-irmt-qgis/issues/198)
=> Add warnings

svir/dialogs/load_npz_as_layer_dialog.py, svir/metadata.txt, svir/test/test_load_npz_as_layer.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/193
I've also re-added the selection of the `poe` for `uhs`, because now we want to download data only for the chosen poe.
=> Add a checkbox to load only the selected data from npz

svir/dialogs/drive_oq_engine_server_dialog.py, svir/help/source/14_driving_the_oqengine.rst
Fixes https://github.com/gem/oq-irmt-qgis/issues/207
=> Rename "Run Risk" button into "Continue" and update the corresponding documentation

svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/222
=> Fix behavior of 'cancel' button in the dialogs that load OQ Engine outputs

README.md
...suggesting the users to use the 32 bit version.
See also https://github.com/gem/oq-irmt-qgis/issues/224
=> Indicate in the README that the Windows 64 bit version has issues

svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/232
=> Fix cascade refreshing of comboboxes while selecting rlz in gmf_data

svir/dialogs/viewer_dock.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/243
=> Improve the size policy of the Viewer Dock, to look better also in small screens

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/274
=> Fix attempt to point to a calculation that is no more in the list

.travis.yml
For now we are restoring a manually generated dump. It will then updated by Engine's Travis.
=> Run integration tests into the Travis testing suite

.travis.yml
Now using http://artifacts.openquake.org/travis/oqdata.zip
=> Update links in .travis.yml following oq-engine/2908

svir/test/integration/test_drive_oq_engine.py
Companion of https://github.com/gem/oq-engine/pull/2931
=> Reduce expected_num_calcs from 16 to 15

svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/294
=> Make sure that integration tests load all loadable output types

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
The widget driving the OQ-Engine was not handling this exception yet.
=> Handle LocationParseError exception

svir/dialogs/viewer_dock.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/307
=> Enable changing output type only if layer has no type

scripts/run-tests.sh, svir/dialogs/viewer_dock.py
Plugin tests on Jenkins were broken (and have been like that for a while). Furthermore, they were only running unit tests.
=> Let Jenkins run unit and integration tests and build doc

svir/dialogs/viewer_dock.py, svir/metadata.txt
Added a check on the status code returned by the oq-engine server 'extract' API, displaying an error message in case of failure.
=> Check status code when calling the 'extract' API

.travis.yml
Moved to https and added `-L` to allow changes to the url in the future
=> Fix curl and artifacts url in travis yaml

scripts/run-tests.sh
This was broken since we moved under https
=> Update curl in run-tests.sh to follow redirects

svir/dialogs/viewer_dock.py, svir/metadata.txt
This was requested by Cata, to have consistency with the visualization of hazard curves
=> Add multiselect for rlzs or stats in visualization of aggregated loss curves

svir/calculations/process_layer.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/340
=> Fix check of layer capabilities, to work regardless from the locale

svir/dialogs/viewer_dock.py, svir/recovery_modeling/recovery_modeling.py
Add a warning about the following issue: https://github.com/gem/oq-irmt-qgis/issues/224
=> If error occurs on importing matplotlib, warn about possible 64bit QGIS issues

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/275
=> If a selected calculation is running, its outputs will be listed on completion

svir/calculations/process_layer.py, svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/select_input_layers_dialog.py, svir/dialogs/transformation_dialog.py, svir/irmt.py
Addresses https://github.com/gem/oq-irmt-qgis/issues/253
=> If a layer can't be edited, show message in message bar

svir/irmt.py
Leveraging the functionality introduced in https://github.com/gem/oq-irmt-qgis/pull/357
=> Set embedded oq standalone apps as experimental

svir/dialogs/settings_dialog.py
It fixes a corner case that happened to Daniele
=> On settings updated, reset standalone apps only if available

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
=> Fix button showing parameters for a oq-engine calculation

svir/dialogs/viewer_dock.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/369
=> Fix visualization of UHS in case PGA is not present

svir/dialogs/connection_profile_dialog.py, svir/dialogs/settings_dialog.py, svir/metadata.txt, svir/ui/ui_connection_profile.ui, svir/ui/ui_settings.ui, svir/utilities/shared.py, svir/utilities/utils.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/372
=> Management of multiple connection profiles

svir/dialogs/settings_dialog.py, svir/metadata.txt, svir/ui/ui_settings.ui, svir/utilities/shared.py, svir/utilities/utils.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/373
=> Add log level setting and truncate long messages in message bar

svir/dialogs/load_hmaps_as_layer_dialog.py
With this change the plugin can read the hazard maps produced by the latest engine.
=> Companion of https://github.com/gem/oq-engine/pull/3446

svir/dialogs/viewer_dock.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/386
=> Fix agg_curves-[rlzs/stats] GUI initialization

svir/dialogs/load_hmaps_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/390
=> Enable loading hmaps corresponding to all IMTs and PoEs

docker/Dockerfile
=> Docker file must use debian-ltr now

svir/dialogs/viewer_dock.py, svir/test/integration/test_drive_oq_engine.py
Needed after the changes introduced in https://github.com/gem/oq-engine/pull/3505
=> Fix reading damage states

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Partially addressing https://github.com/gem/oq-irmt-qgis/issues/409
=> Improve error message in case the engine is not running

svir/dialogs/download_layer_dialog.py, svir/metadata.txt, svir/utilities/sldadapter.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/420
It's the same problem that was partially solved in https://github.com/gem/oq-irmt-qgis/pull/367
=> Fix all occurrences of Qt.Qt.Something

svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/430
=> Deselect the layer containing points after aggregating loss/damage by zone

svir/dialogs/viewer_dock.py
This https://github.com/gem/oq-irmt-qgis/pull/429 was incomplete. Now it should be ok.
=> Fix deselection of tag with star

svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt
Fixes a styling issue introduced in https://github.com/gem/oq-irmt-qgis/pull/425
=> Fix styling of scenario damage after aggregating by zone

svir/dialogs/load_dmg_by_asset_as_layer_dialog.py, svir/dialogs/load_losses_by_asset_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/utilities/utils.py
Companion of https://github.com/gem/oq-engine/pull/3604
=> Retrieve loss types from composite_risk_model.attrs

svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/435
=> Style ruptures by trt or by magnitude

svir/dialogs/load_dmg_by_asset_as_layer_dialog.py, svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_losses_by_asset_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/410
=> Loading GMFs, show GMPEs instead of realizations

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt, svir/ui/ui_viewer_dock.ui
Fixes https://github.com/gem/oq-irmt-qgis/issues/445
@pslh: I'm displaying the hostname instead of the name of the connection profile. This is easier to implement, and it looks good enough for me.
=> Make versions more visible and stored in layers

docker/Dockerfile, scripts/compile-strings.sh, scripts/run-env-linux.sh
Update the docker container and some scripts
=> Update docker for testing to QGIS 3 and Bionic

svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/457
=> Enable ok btn depending on checked aggregation gbx and selected zonal layer

README.md, svir/dialogs/viewer_dock.py, svir/help/source/00_installation.rst, svir/recovery_modeling/recovery_modeling.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/466
=> Fix matplotlib, using Qt5Agg

.travis.yml, docker/Dockerfile, docker/README.md
See https://ci.openquake.org/job/builders/job/oq_irmt_qgis-builder/41/
=> Add ghostscript for manual builds

svir/dialogs/viewer_dock.py, svir/metadata.txt
Companion of https://github.com/gem/oq-engine/pull/3862
Fixes https://github.com/gem/oq-irmt-qgis/issues/463
=> Visualize loss curves aggregated by tag

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/481
=> Sort output_list of a oq-engine calc by name instead of id

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt, svir/utilities/shared.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/446
=> Add loaders for `dmg_by_event` and `losses_by_event`, from csv (disabled for event-based calculations)

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/493
In the same PR, I am also fixing https://github.com/gem/oq-irmt-qgis/issues/494
(suggesting the user where to look, in case feedback is displayed outside the dialog that drives the OQ-Engine)
=> Do not set "waiting" cursor while refreshing engine calc list

svir/dialogs/load_hcurves_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/485
=> Load hazard curves for selected realization/statistic and intensity measure type

docker/run_make.sh
Fixes https://ci.openquake.org/job/qgis/job/oq_irmt_qgis-builder/52/
=> Make sure .local/share exists in HOME

svir/dialogs/load_hmaps_as_layer_dialog.py
It was broken by the change in https://github.com/gem/oq-engine/pull/3963.
=> Fixed load_hmaps

svir/dialogs/upload_dialog.py, svir/thread_worker/upload_worker.py
Added new changes to upload project from qgis2 with correct style
=> Upload project new platform wip

svir/dialogs/upload_dialog.py, svir/metadata.txt, svir/utilities/sldadapter.py
When we ported the plugin from qgis2 to qgis3, we left a TODO in the styling process. This PR should fix styles in general. I will merge this part also into the branch that fixes the uploading of layers to the new platform.
=> Port styling to qgis3

svir/dialogs/load_hmaps_as_layer_dialog.py, svir/metadata.txt
https://github.com/gem/oq-irmt-qgis/pull/499/files broke a corner case that is not tested by integration tests. I should add a test for that. Meanwhile, this PR fixes https://github.com/gem/oq-irmt-qgis/issues/507
=> Fix loading hmaps into one layer per rlz or stat

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/show_console_dialog.py, svir/help/source/14_driving_the_oqengine.rst, svir/metadata.txt, svir/ui/ui_drive_engine_server.ui
Fixes https://github.com/gem/oq-irmt-qgis/issues/513
=> Add the possibility to abort a OQ-Engine calculation

svir/irmt.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/514
=> Fix viewer dock toolbar button checked/unchecked status

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/show_console_dialog.py, svir/metadata.txt
I hope it fixes https://github.com/gem/oq-irmt-qgis/issues/503
I've tried these changes in the VM, and the problem did not occur anymore. We should test it more thoroughly and see if the issue is actually solved.
=> Improve stability of the connection with the OQ-Engine server

svir/dialogs/load_losses_by_asset_as_layer_dialog.py, svir/tasks/extract_npz_task.py
Finally I can see on travis what it is going on, see for instance https://travis-ci.org/gem/oq-irmt-qgis/builds/497984
```
Loading output type hcurves...
Extracting http://172.17.0.1:8800/v1/calc/11/extract/hcurves
ok
(loading time: 32.6605 sec)
Loading output type hmaps...
Extracting http://172.17.0.1:8800/v1/calc/11/extract/hmaps
ok
(loading time: 1.8672 sec)
```
=> Added a print with the extract URL

svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py
Companion of https://github.com/gem/oq-engine/pull/4569
=> Fixed the management of realizations

svir/test/integration/test_drive_oq_engine.py
I want to fix integration tests for master, while I am still working on the stuff for CRAVE.
=> Skip integration tests for ebrisk

svir/dialogs/load_inputs_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/563
=> Add loaded layers on top

.travis.yml, scripts/make_doc.sh, svir/how_to_run_tests.txt
=> Test documentation

svir/utilities/utils.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/574
=> Use the showMore parameter in message bars and improve displaying tracebacks

svir/metadata.txt, svir/ui/ui_load_output_as_layer.ui
It should make dialogs usable also on low resolution screens
=> Set dialogs to load outputs as layers, using a scrollable area for selectors

svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/metadata.txt
Companion of https://github.com/gem/oq-engine/pull/4813
=> Reflected change in the realizations

svir/calculations/calculate_utils.py, svir/calculations/process_layer.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/dialogs/recovery_modeling_dialog.py, svir/dialogs/recovery_settings_dialog.py, svir/dialogs/viewer_dock.py, svir/irmt.py, svir/metadata.txt, svir/recovery_modeling/recovery_modeling.py, svir/test/functional/test_recovery_modeling.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/581
=> Optimize getFeatures, ignoring geometries if unneeded and getting only necessary fields

.travis.yml, scripts/run_integration_tests.sh, svir/dialogs/drive_oq_engine_server_dialog.py, svir/test/integration/test_drive_oq_engine.py
In order to find input files, I am cloning the oq-engine also in the docker, retrieving and running the first available risk demo calculation.
=> Add an integration test running a hazard calculation and a risk one on top of it, then removing both

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/602
=> Avoid downloading useless files when using the "extract" API instead

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt, svir/utilities/shared.py
Companion of https://github.com/gem/oq-engine/pull/4976 (addressing https://github.com/gem/oq-engine/issues/4973)
=> Replace loader for 'sourcegroups' with 'events'

README.md, svir/help/source/00_installation.rst, svir/metadata.txt
and remove a warning about an issue with matplotlib 3.0.0 on mac and windows.
Companion of https://github.com/gem/oq-engine/pull/4984
=> Add a note to manual and README about updating SSL certificates bundle on MacOS

README.md, svir/help/source/00_installation.rst
Companion of https://github.com/gem/oq-engine/pull/4987
=> Add to README and to installation instructions a link to our code mirror on Gitea

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/618
=> Show buttons to load layers from OQ-Engine outputs as first buttons

svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/ui/ui_viewer_dock.ui
Fixes https://github.com/gem/oq-irmt-qgis/issues/605
=> Disable output type dropdown selector in the Data Viewer

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt, svir/utilities/shared.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/640
=> Add loader for agglosses from csv as table

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/641
=> Add possibility to download OQ-Engine input files as zip

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_asset_risk_as_layer_dialog.py, svir/dialogs/load_basic_csv_as_layer_dialog.py, svir/dialogs/load_dmg_by_asset_as_layer_dialog.py, svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/load_hcurves_as_layer_dialog.py, svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_inputs_dialog.py, svir/dialogs/load_losses_by_asset_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/dialogs/load_uhs_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py, svir/utilities/utils.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/649
TODO:
=> Store layer metadata (title and keywords) read from calculation parameters

scripts/make_doc.sh, scripts/run_integration_tests.sh, scripts/run_unit_tests.sh
This is a test to check if the cause of master becoming broken today (being green yesterday) was due to issues introduced in the latest qgis docker
=> Use qgis:final-3_8_3 instead of qgis:latest

svir/dialogs/viewer_dock.py
Companion of https://github.com/gem/oq-engine/pull/5110
=> Fix encoding/decoding stats

svir/test/unit/test_multi_select_combo_box.py, svir/ui/multi_select_combo_box.py
and fix some minor issues in the widget, that were spotted while adding tests.
Fixes https://github.com/gem/oq-irmt-qgis/issues/657
=> Add unit tests for MultiSelectComboBox

svir/ui/complex_line_edit.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/664
=> In MultiSelectComboBox change colors depending on enabled/disabled widget

svir/dialogs/viewer_dock.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/668
=> Fix some issues in the recovery modeling GUI

svir/irmt.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/669
=> Fix reconnecting signals/slots when the plugin is reloaded

svir/dialogs/load_output_as_layer_dialog.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/679
=> Pre-populate zonal layer dropdown when the zonal layer is added

svir/dialogs/drive_oq_engine_server_dialog.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/674
=> Avoid selecting row in calc list

scripts/run_integration_tests.sh, scripts/run_unit_tests.sh, svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_basic_csv_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/test/integration/test_drive_oq_engine.py, svir/utilities/utils.py
First, I am making sure that the integration test fails because we are using tab as separator instead of comma. Then I am fixing the separator.
=> Fix loader for ruptures

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/viewer_dock.py, svir/irmt.py, svir/ui/ui_drive_engine_server.ui
Fixes https://github.com/gem/oq-irmt-qgis/issues/675
=> Keep all tag values selectors visible instead of using tabs

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
This reverts commit 119fe83bb5869f731a5284edc624199ed96507fd.
=> Fix a regression in the management of the list of OQ-Engine calculations

svir/dialogs/viewer_dock.py
Now it is simpler.
Good vacation @ptormene !
=> Fixes some encoding error due to changes on the engine side

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_basic_csv_as_layer_dialog.py, svir/dialogs/load_csv_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/metadata.txt, svir/utilities/shared.py
Another step towards https://github.com/gem/oq-irmt-qgis/issues/401
=> Load ruptures using the extract api instead of loading the exported csv

svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py
Companion of https://github.com/gem/oq-engine/pull/5281
=> Load compressed rupture boundaries

svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py
Leveraging the change made in https://github.com/gem/oq-engine/pull/5279/files
=> Filter ruptures by minimum magnitude

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/dialogs/show_console_dialog.py, svir/dialogs/viewer_dock.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/644
TODO:
=> Extract agg_curves instead of agg_curves-stats and agg_curves-rlzs

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_asset_risk_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/ui/ui_drive_engine_server.ui
Fixes https://github.com/gem/oq-irmt-qgis/issues/706
Also fixes https://github.com/gem/oq-irmt-qgis/issues/705
WIP:
=> Add the possibility to filter the list of calculations by job id

svir/dialogs/load_asset_risk_as_layer_dialog.py, svir/dialogs/load_dmg_by_asset_as_layer_dialog.py, svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/load_hcurves_as_layer_dialog.py, svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_losses_by_asset_as_layer_dialog.py, svir/dialogs/load_uhs_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/708
All calls to the extract api were already logged, but in some cases the user might have been confused by the fact that nothing immediately visible happened after pressing some buttons. Here I am adding some notifications to the message bar, to make things more explicit.
=> Notify when starting an extract task

svir/irmt.py
Improvement of https://github.com/gem/oq-irmt-qgis/pull/650
=> Save/restore only canvas highlight color (not project)

.travis.yml, svir/dialogs/load_asset_risk_as_layer_dialog.py, svir/dialogs/load_dmg_by_asset_as_layer_dialog.py, svir/dialogs/load_losses_by_asset_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/tasks/extract_npz_task.py, svir/utilities/utils.py
Companion of https://github.com/gem/oq-engine/pull/5477
=> Use `numpy.load(allow_pickle=False)` while extracting data from the OQ-Engine

svir/dialogs/drive_oq_engine_server_dialog.py, svir/utilities/utils.py
Companion https://github.com/gem/oq-engine/pull/5839/
=> Use /extract/oqparam

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/714
=> Enable loaders for dmg_by_event and losses_by_event also for event_based

svir/dialogs/load_asset_risk_as_layer_dialog.py, svir/dialogs/load_avg_damages_rlzs_as_layer_dialog.py, svir/dialogs/load_avg_losses_rlzs_as_layer_dialog.py, svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/load_hcurves_as_layer_dialog.py, svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/tasks/extract_npz_task.py, svir/utilities/utils.py
Now the OQ-Engine return only the relevant events, so the list of event ids might likely have missing values, so we need to help the user identifying the closest event id with respect to the initially chosen one.
I am also fixing some minor aspects due to recent changes in the engine and in the numpy api.
=> Relevant events

svir/apidoc/svir.dialogs.rst, svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_damages_rlzs_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/dialogs/recovery_modeling_dialog.py, svir/dialogs/viewer_dock.py, svir/help/source/13_recovery_modeling.rst, svir/metadata.txt, svir/recovery_modeling/recovery_modeling.py, svir/test/integration/test_drive_oq_engine.py, svir/ui/ui_recovery_modeling.ui, svir/utilities/shared.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/747
=> Rename avg_damages-rlzs -> damages-rlzs and avg_damages-stats -> damages-stats

svir/dialogs/load_hmaps_as_layer_dialog.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/759
=> Avoid creating empty groups of hmaps

svir/ui/ui_settings.ui
Fixes https://github.com/gem/oq-irmt-qgis/issues/761
=> Make the settings dialog scrollable

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py, svir/utilities/shared.py
Due to changes in the engine (see https://github.com/gem/oq-engine/pull/7230)
Fixes https://github.com/gem/oq-irmt-qgis/issues/788
=> Removed output agg_curves-rlzs

svir/test/integration/test_drive_oq_engine.py
It should be a slightly more realistic simulation of the actual behavior of the widgets we want to test.
=> Use QTest.mouseClick instead of dlg.accept

.github/workflows/qgis_383.yml, .github/workflows/qgis_latest.yml, .github/workflows/qgis_ltr.yml, README.md, scripts/doc_upload.sh, scripts/make_doc.sh, svir/Makefile, svir/help/source/00_installation.rst, svir/help/source/14_driving_the_oqengine.rst, svir/help/source/15_viewer_dock.rst, svir/metadata.txt
Same as https://github.com/gem/oq-irmt-qgis/pull/802, to be merged in master for release v3.15.2
=> Improve makefile for version 3.15

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/816
=> Properly reset the button to retrieve calculation parameters

svir/dialogs/load_hmaps_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/822
=> No empty layer groups

svir/metadata.txt, svir/ui/ui_text_browser.ui
Fixes https://github.com/gem/oq-irmt-qgis/issues/823
=> In console/report text area, use Courier monospace font and set NoWrap

svir/dialogs/viewer_dock.py, svir/metadata.txt
While fixing the ylabels in a previous PR I did not fix properly the label for occupants and residents.
=> Fix people ylabel

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py
Companion of https://github.com/gem/oq-engine/pull/9131
Fixes https://github.com/gem/oq-irmt-qgis/issues/839
=> Add visualization of aggcurves and aggcurves-stats for event_based_damage

.github/workflows/qgis_ltr_engine_releases.yml, svir/test/integration/test_drive_oq_engine.py
Companion of https://gitlab.openquake.org/openquake/oq-risk-tests/-/merge_requests/83
Tests are green: https://github.com/gem/oq-irmt-qgis/actions/runs/7813589467/job/21313049020
=> Enable daily tests for risk workshop demos

.github/workflows/qgis_ltr_engine_releases.yml, .github/workflows/test.yml, svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/810
Fixes https://github.com/gem/oq-irmt-qgis/issues/746
See the screenshots below:
=> Change event - gsim selection for scenario / fix header of avg_losses-rlzs_aggr in case collect_rlzs=True

svir/dialogs/viewer_dock.py
Companion of https://github.com/gem/oq-engine/pull/10018
Fixes https://github.com/gem/oq-irmt-qgis/issues/783
=> Include the total losses in the selectable loss types when wisualizing aggcurves

svir/dialogs/load_damages_rlzs_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/utilities/utils.py
The engine was moved back to the previous behavior (https://github.com/gem/oq-engine/pull/10124)
=> Revert `https://github.com/gem/oq-irmt-qgis/pull/873`

svir/dialogs/load_damages_rlzs_as_layer_dialog.py, svir/utilities/utils.py
Following changes made in https://github.com/gem/oq-engine/pull/10158/files
=> Fix loader for damages_rlzs, getting damage states and reading values as loss_type-dmg_state

svir/dialogs/load_inputs_dialog.py, svir/metadata.txt
We might prefer to do the renaming engine-side.
=> Rename multi_peril_csv -> multi_peril_file
