iso_19115_template.xml, metadata_utilities.py, svir.py
Partially addressing https://bugs.launchpad.net/oq-svir/+bug/1409725
Note: unfortunately, the current version of Geonode does not put the license into a "license" metadata field, but into the "other restrictions" field. We can merge the current solution anyway, and wait for the next version of Geonode for further changes.
=> Add license to layer restrictions

calculate_utils.py
ProcessLayer.delete_attributes deletes attributes using LayerEditingManager, which starts each operation with layer.startEditing() and ends with layer.commitChanges() and layer.updateExtents().
=> When deleting attributes in case a calculation fails, use ProcessLayer

svir.py
This is a one-line fix, but important. It solves a very annoying issue that might occur when the qgis project contains an empty project definition. In that case, the plugin attempts to parse the project definition's json, which is an empty string, so it raises an exception.
I added a check to avoid that.
=> Fix corner case in which the project definition is defined in the qgis project, but it's empty

svir.py, transformation_dialog.py, ui/ui_upload_settings.py, ui/ui_upload_settings.ui, upload_settings_dialog.py, utils.py
Before this change, after uploading a project to the Platform, a second user couldn't know which of the available layer's fields contains the zone labels used by the layer's creator. This PR forces the user to specify such field from a combobox, before proceeding with the upload. Such field gets saved in `project_definition['zone_label_field']`.
Instead of this approach, we could implement different solutions, but I'm not able to figure out any better one. For instance, we could save what zone id field was used when (and only if!) performing "loss aggregation by zone", and set such field as the default selection. In any case, the field might possibly be a numeric attribute, not so easily usable as a "label" to be displayed in Ben's charts in the web viewer. Therefore I believe it's …
=> Force selecting the field containing the zone label, before uploading to the Platform

svir.py
Render the layer's style also while opening the weighting dialog (without waiting for any changes in the tree).
Save the layer's original style when the weighting dialog is opened, so it can be restored if "Cancel" is pressed in the dialog. 
Comment out lines that were resetting the fill to the style for null values. It did not work properly and it colored the zones with null values, instead of removing the fill.
=> Fix some styling issues

metadata_utilities.py, svir.py, weight_data_dialog.py
In that case, for now, we just use the most recent project definition.
In a later PR we will need to allow the user to select one of the available project definitions.
We will also need to have an additional workflow, to update one of the projects on the platform, adding only a new project definition to that (as the web viewer now does).
This PR also explicitly sets the parameters in json.dumps, in order to make the project definition format consistent in all cases, including the server-side occurrences.
=> Handle the case in which multiple project definitions are available for a single project

metadata.txt, resources_rc.py, svir.py, weight_data_dialog.py
* Fix a corner case in which the user attempts to set weights and there's no available project definition.
* Avoid printing the "parent" key into the project definition string
=> Small fixes

settings_dialog.py
In the OQ-Platform connection settings, the user might set a host like `https://platform-dev.openquake.org/`, ending with `/`. Before this PR, this produced some weird behaviors, because the host was recognized, but the `/` interfered with the platform's API. In order to avoid this, we strip the hostname and remove the ending `/` if present.
=> If the (stripped) hostname ends with '/', remove it

import_sv_data.py, utils.py
There were some corner cases in which the login failed and the plugin broke instead of displaying an error message in the QGIS message bar. I also set a timeout of 10 seconds for the login, otherwise the server could not respond for a long time (also blocking the GUI).
=> Better manage platform login exceptions

calculate_utils.py, svir.py
Also avoid the plugin to break when the selected project definition is invalid (in such case, the indices are not recalculated and the style is not updated)
=> Recalculate indices after selecting a different project definition

svir.py, upload_settings_dialog.py
In the "upload project to platform" dialog, if the project already has a title, use it instead of the default one.
=> Pre-populate the title field before uploading a project to the platform

projects_manager_dialog.py, svir.py, ui/ui_upload_settings.py, ui/ui_upload_settings.ui, upload_metadata_dialog.py, upload_settings_dialog.py, utils.py
This PR completes the loop between the QGIS plugin and the web viewer.
When a project is loaded from the platform, the platform layer's id is saved into the project definitions. This information is retrieved when the user chooses to upload a project to the platform. In such situation, the user can decide to upload the current work as a new project (creating a new geonode layer) or to use the saved layer's id to update the corresponding project on the platform. The updating procedure uses the same API we made to allow the web viewer to append new project definitions into existing projects.
=> Enable to add a new project definition to a project already present on the platform

projects_manager_dialog.py, svir.py, ui/ui_projects_manager_dialog.py, ui/ui_projects_manager_dialog.ui
This PR adds to the "Project definitions manager" a "Title" line edit and a "Description" text edit, that dynamically update the corresponding fields in the selected project definition.
NOTE: the project definition's "Description" is a brief summary of that specific project definition, and does NOT correspond to the "Abstract", which instead describes the whole layer and that is stored into the GeoNode layer's metadata.
=> Simplify editing project definition title and description

upload_metadata_dialog.py
Otherwise, simply use the default basic style, without attempting to convert the qgis style.
This situation can happen when we upload a layer that hasn't been styled by the plugin (for instance, when downloading some socioeconomic indicators and then uploading the layer without any further analysis). We might consider in the future if such situation should be allowed, or if we want to force the users to calculate some aggregated indices before uploading their project to the platform.
=> Apply style to the uploaded layer only if the style is rule-based (the only one we implemented yet)

metadata.txt, projects_manager_dialog.py, ui/ui_projects_manager_dialog.py, ui/ui_projects_manager_dialog.ui
Based on https://github.com/gem/oq-svir-qgis/pull/65
In addition to the new button for cloning a project definition, this PR fixes a bug in the form for updating the current project definition. Now, when the raw text is modified, the current project definition is updated, before it can be overwritten by changing the title or description.
=> Add a button to the project manager, to make a copy of the selected project definition

metadata.txt, svir.py, ui/ui_weight_data.py, ui/ui_weight_data.ui, utils.py, weight_data_dialog.py
Based on https://github.com/gem/oq-svir-qgis/pull/65
An additional dropdown menu is added to the weighting dialog, enabling the user to select which field should be used by the plugin to automatically style the layer. This makes possible, for instance, to quickly style the layer by one of the socioeconomic themes (that now are stored as fields in the layer).
If none is selected from this dropdown menu, the automatic behavior of the tool is the old one (check if it's possible to style by the IRI, otherwise attempt to style by the SVI, otherwise by the RI... or do nothing).
=> Add a dropdown menu to select the field to be used for styling the layer

import_sv_data.py, svir.py
QGIS 2.10 in unable to import multipolygons from CSV if there are whitespaces between polygons.
This quick fix removes those whitespaces before letting QGIS import the CSV.
Such change should be removed as soon as the bug will be fixed in QGIS.
=> Fix a QGIS 2.10 issue with CSV import

svir.py, utils.py, weight_data_dialog.py
This is to avoid the user to accidentally close the weighting dialog, losing all the unsaved changes. The same can be easily re-used for other dialogs, but it doesn't look necessary elsewhere (so far) and it might be a little annoying for the user to be asked to confirm everywhere, so it has been implemented only for the weighting dialog.
=> Show a confirmation/warning dialog when pressing "cancel" or "close" in the weighting dialog

weight_data_dialog.py
We noticed that changing the field by which we wanted to style the layer, did not immediately produce a change to the style. Changes were displayed from the second time it was switched. I investigated, and I found out it was due to the fact we were not emitting a signal to declare the project definition was changed, so the styling was not performed right away.
Emitting the json_updated signal, the change becomes immediately visible, so it is possible to keep the weighting dialog open while styling by different fields.
It is a one-line change, but it produces an important improvement to the user-experience.
=> Immediately style the layer by the selected field, even without closing the weighting dialog

svir.py
Otherwise an exception could happen (which was not catched properly)
=> Fix corner case in field transformation, updating project definition only if available

ui/ui_weight_data.py, ui/ui_weight_data.ui, weight_data_dialog.py
Addressing https://bugs.launchpad.net/oq-svir/+bug/1477029
While the user is building the project definition using the weighting dialog, the tool keeps recalculating the composite indices whenever any change is made to the model. The advantage of it is that the layer is styled dynamically, displaying in real-time the effects produced by each change. The drawback is that,
when a project is big, the re-calculations are time-consuming and therefore the weighting dialog becomes quite slow and not so responsive.
With this PR, a new checkbox is added to the dialog. It is checked by default, activating the on-the-fly calculations (the behavior of the tool before this PR). The user can uncheck it, preventing the tool from doing the re-calculations on-the-fly, therefore allowing to build the …
=> Add checkbox to weighting dialog, to toggle on-the-fly calculations

resources/js/svir_viewer_d3_tree.js
Addressing https://bugs.launchpad.net/oq-svir/+bug/1490994
Side note: I've also renamed some counters, because my editor's syntax checker kept complaining about defining variables with the same name of already existing ones (even if they are in different scopes).
=> Show a warning dialog when attempting to add a node and no more numeric fields are available

process_layer.py, svir.py, upload_settings_dialog.py, utils.py
Based on https://github.com/gem/oq-svir-qgis/pull/83
We might want to set a maximum threshold for the complexity of geometries to be uploaded to the platform. With this PR, the vertices of the active layer's geometries are counted when the "upload" dialog is opened. This is still WIP, and we need to decide if and when we want to display the vertices count to the user, and if we want to forbid to upload something too complex or at least to display some kind of warning, also to inform the user that the web viewer will not be able to manage an exceedingly complex project.
=> Count the active layer's vertices before uploading a project to the platform

svir/calculations/aggregate_loss_by_zone.py, svir/calculations/calculate_utils.py, svir/calculations/process_layer.py, svir/calculations/transformation_algs.py, svir/test/test_transformations.py
Importing `QPyNullVariant` from `qgis` doesn't work anymore.
It has to be imported from `PyQt4.QtCore` instead.
=> Fix import error raised by QGIS 2.12 when importing QPyNullVariant

svir/metadata.txt, svir/utilities/sldadapter.py
Before QGIS version 2.12, `Rule` has the method `symbols()`,
which is replaced by `symbols2()` in QGIS version 2.12.
Also, before version 2.12, QgsSimpleLineSymbolLayerV2 always has the method `brushStyle`, but from version 2.12 this is not always true.
With this PR, the plugin should work with both QGIS versions.
Fixes https://github.com/gem/oq-irmt-qgis/issues/96
=> Fix style generation for QGIS version >= 2.12

svir/__init__.py
I've tested this on a windows laptop with QGIS 2.12 that wasn't able to load the plugin (see https://github.com/gem/oq-irmt-qgis/issues/102) and it seems to solve the problem.
The issue seems related to a missing dependency (no setuptools installed).
=> Fix #102 - Workaround for windows missing 'pkg_resources'

svir/third_party/requests/packages/urllib3/contrib/pyopenssl.py
Don't break when OpenSSL has SSLv3_METHOD disabled.
this is needed at least for ubuntu 15.10
see http://stackoverflow.com/questions/28987891/#answer-29081240
=> Don't break when OpenSSL has SSLv3_METHOD disabled.

svir/metadata.txt, svir/thread_worker/upload_worker.py
For some strange reason, if the xml attached to the shapefile is opened in `'r'` mode instead of `'rb'`, the uploading does not work on windows (but it still works on ubuntu).
Changing it to `'rb'` make it works on both systems.
=> Fix uploading on windows

svir/calculations/calculate_utils.py, svir/dialogs/weight_data_dialog.py, svir/irmt.py, svir/metadata.txt, svir/utilities/utils.py
3 bugs fixed:
* We had a HUGE memory issue in the recursive procedure used to collect the field names in a project definition. It made the application exponentially slower the more the project definition became complex. It was causing the application to go out of memory even with relatively simple projects. Now that it is solved, things should be much faster and the weighting dialog shouldn't freeze even for much bigger and complex projects.
* When making the project definition track transformed fields, we had a problem in case one of the fields could not be transformed correctly (e.g. a corner case in which min-max transformation couldn't be performed because all the input values are equal to each other). In such case, the project definition was set to point to the transformed attribute, …
=> Fix memory issue in weighting dialog (and more)

svir/utilities/utils.py
It was returning also an undesired newline after the version number, that broke the searching functionality in the documentation.
=> Fix get_irmt_version function

svir/irmt.py, svir/metadata.txt
Fix #129 
When automatically restyling a layer after a calculation, we were setting no-pen and no-brush in a part of the legend. If users wanted to apply a different style, they needed to explicitly reset the brush and pen style. In order to avoid this, we are not hiding that part of the legend anymore, and we are showing it with with a color that makes sense.
=> Avoid removing border and fill from style

svir/dialogs/select_input_layers_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/135
`ProcessLayer.is_type_in` raises an exception if the layer's wkbType is unknown. This exception was not catched properly by the widget used to select layers for aggregating points in polygons. The undesired effect was that the presence of any "broken" layer in the list of available layers broke the tool, making it impossible to perform the aggregation even using "good" layers.
I fixed this wrong behavior by using the built-in `QgsVectorLayer.geometryType()` instead, which does not raise any exception in case the type is unknown.
NOTE: for some reason that is not so clear to me, QGIS has two different ways to classify the geometry type of a layer. One is by the enum QGis.GeometryType and one is by wkbType. In this case, the …
=> Change check on geometry type

svir/calculations/aggregate_loss_by_zone.py, svir/metadata.txt
SAGA's clippointswithpolygons produces a shapefile with laundered names (reduced to max 10 characters). Therefore, the original field names can't be found in the output layer, unless we keep a map of old fieldnames -> laundered fieldnames.
In addition to this, I had to change the approach that was used to identify the field name for zone ids. Previously, we were assuming the loss_layer_plus_zone_ids would differ with respect to the loss_layer only by one additional field containing zone ids. But, as mentioned above, other field names could be laundered. So, the only thing we can do is to assume that the new field containing zone ids will be added "after" the existing ones, and to get the name of the last field.
Tests are green.
=> Fix workflow using SAGA, in case of long field names

svir/Makefile, svir/test/test_recovery_modeling.py
For some strange reason, the Makefile was intentionally returning an exit code 0 even in case of failing tests. This caused Travis to pass even in case of failing tests.
=> Let Travis check fail when a test fails

svir/Makefile
to avoid reaching the threshold of 10MB per plugin
=> Reduce size of pdf manual in the package

svir/dialogs/load_npz_as_layer_dialog.py, svir/metadata.txt
Fix a bug that was introduced in https://github.com/gem/oq-irmt-qgis/pull/162
It was due to the fact that the methods named `addFeatures` in the QgsVectorLayer class and in the layer's dataProvider are slightly different (the former returns a boolean, and the latter returns a tuple; the former pre-selects features, the latter does not). I disabled the automatic selection, setting the makeSelected argument to False.
=> Fix adding features when importing data from oq-engine

svir/dialogs/settings_dialog.py, svir/ui/ui_settings.ui
Fixes https://github.com/gem/oq-irmt-qgis/issues/171 (an issue that was found on Mac and Windows)
Instead of using the more convenient (but less compatible) QgsColorButtonV2, I replaced it with a QPushButton opening a QColorDialog.
I first attempted to set the background color of buttons using their palettes, but it modified only the border of the button, so I had to set the stylesheet instead.
This implementation should run on Ubuntu, Mac OS X and Windows, but I still have to test it on Mac and Windows, to make sure it actually solves the issue.
=> Use standard widgets to select colors for classification

svir/irmt.py
Otherwise, it is possible to load gmf data while driving the engine and pressing "Load npz as layer", but it is impossible, for instance, to load a npz produced by someone else and not downloadable from your running engine.
=> Enable menu item to load gmf data from npz

svir/dialogs/viewer_dock.py, svir/metadata.txt
When the plot is crowded, differentiating markers makes it easier to identify the correspondence between curves and legend items.
=> Plot markers in hazard curves and uniform hazard spectra

svir/dialogs/drive_oq_engine_server_dialog.py, svir/irmt.py, svir/metadata.txt
The unification removes some duplication and improves readability. I am also handling the SSLError exception, that was not managed before and that stores the error message in a peculiar way.
I am also fixing the check on the connection, that has to be done whenever the dialog that drives the engine is created or opened.
Furthermore, I'm now checking both in cases in which the engine server's LOCKDOWN parameter is set to True or to False.
Fixes https://github.com/gem/oq-irmt-qgis/issues/183
=> Unify the management of exceptions while driving the oq-engine

svir/dialogs/viewer_dock.py, svir/metadata.txt
I made three main changes:
1. I found out how to remove all widgets from a layout, without having to remove them explicitly one by one
2. I picked a better size policy for all widgets so, for instance, the plotting area tends to occupy all the available space
3. I fixed https://github.com/gem/oq-irmt-qgis/issues/187, that was caused by an unnecessary call to adjustSize (the size is adjusted automatically anyway)
=> Improve viewer layout

svir/calculations/aggregate_loss_by_zone.py
`loss_attrs_dict` was passed to an internal function and it was returned untouched.
=> Remove an unused argument

svir/calculations/aggregate_loss_by_zone.py, svir/dialogs/recovery_modeling_dialog.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/190
While aggregating points by zone, if the original layer contains long names, those names might be laundered to contain max 10 characters. When it happens, the selected original fields that contain damage state probabilities might not be found (not found returns -1), and the recovery modeling workflow would assume probabilities are contained in the field of index -1 (the last one) which instead contains the zone id. This was causing linux to produce bad results and windows to crash.
Here I am fixing it by mapping the original field names and the laundered ones, so the selected fields can actually be found and the calculation produces meaningful results.
While working on this I found out that a previous refactoring of some functions …
=> Map selected fieldnames to laundered names

svir/dialogs/load_npz_as_layer_dialog.py, svir/test/test_load_npz_as_layer.py
Fix https://github.com/gem/oq-irmt-qgis/issues/192
Since the realization name is something like `rlz-XXX`, we don't need to add `rlz-`, otherwise it is duplicated.
=> Remove duplication of rlz in the layer names

svir/utilities/utils.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/198
=> Fix corner case of corrupted setting saved in `color_from` or `color_to`

svir/help/source/15_viewer_dock.rst
Fixes https://github.com/gem/oq-irmt-qgis/issues/204
(it describes something that is available from QGIS 2.18+, but I would not invest time fixing the interaction with OpenLayers Plugin) 
I'm adding to the manual a warning about the fact that the OpenLayers Plugin breaks the behavior of the data viewer, that should highlight the corresponding point in the map when the mouse is moved on a hazard curve. Where the highlighting effect is described, I am adding a warning, explaining how to use tile servers through a built-in QGIS functionality (as suggested by @mbernasocchi), without using any external plugin.
Please note that OpenStreetMap is loaded faster and more efficiently this way, and we can avoid depending on a third-party plugin.
=> Explain how to add openstreetmap without using external plugins

svir/dialogs/load_hcurves_as_layer_dialog.py, svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_losses_by_asset_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_uhs_as_layer_dialog.py, svir/metadata.txt
When a OQ Engine calculation has more than one realization, the corresponding output does not contain results for any of the realizations, but it contains statistical outputs (e.g. mean, quantiles). With the same widget that was used to select one of the available realizations, now it is possible to select the single existing realization or one of the statistical outputs.
Since the method `populate_rlz_cbx` does the same for many loaders, I don't need to override that method in the subclasses anymore.
I've also fixed a little bug in the creation of the layer name for hazard curves.
Fixes https://github.com/gem/oq-irmt-qgis/issues/219
=> Load stats as layers

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Before this change, table cells were automatically resized, based on their contents, so a calculation with a very long description caused the table to become very wide and not so comfortable to browse.
I decided to set a reasonable size for all the columns (because in this case we know a priori how many columns we have and what kind of content they have). When a description is long, its text is wrapped and the size of the row is adapted accordingly.
=> Improve the layout of the list of OQ Engine calculations

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
While scrolling through the list of calculations, the tool keeps polling and refreshing the list, without losing the current scrolling.  But if you click on any button, at the next refresh, the view is scrolled to the top. Therefore we need to keep track of which line was clicked, in order to scroll to that line after refreshing the list.
=> Keep the calculation list scrolled to visualize the latest clicked row

svir/metadata.txt, svir/ui/ui_drive_engine_server.ui
While browsing the list of calculations, it might be good to increase its vertical size, reducing the size of the list of outputs for a chosen calculation; and vice versa.
=> Add a splitter between the list of calculations and the list of outputs

svir/dialogs/viewer_dock.py, svir/irmt.py, svir/metadata.txt
It was a little counter-intuitive to have the viewer visible but disabled, being unable to click on the `x` to close it. With this change, the viewer remains always enabled, but you can hide it by pressing the `x` or the additional toolbar button, and you can re-open it by pressing the toolbar button.
=> Add toolbar button to show/hide the viewer dock

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
The `WaitCursorManager` changes the mouse pointer, to indicate the plugin is busy doing something. If also a message is specified, it is shown into the QGIS message bar. While retrieving the log of a OQ-Engine calculation, we keep getting the calculation's status and the calculation's log, spamming the QGIS message bar with annoying messages. I prefer to keep it more silent, as it already happens while polling the engine server to update the list of calculations.
=> Do not show info messages while polling to get console log of calc

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_dmg_by_asset_as_layer_dialog.py, svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/load_hcurves_as_layer_dialog.py, svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_losses_by_asset_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/dialogs/load_uhs_as_layer_dialog.py, svir/irmt.py, svir/metadata.txt, svir/test/test_load_oq_engine_output_as_layer.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/241
Even with this change, the output type will be automatically selected only right after loading a layer. When another layer is manually selected, the output type in the Viewer Dock will be reset to None. We might change this behavior, for instance reading the output type from the name of the selected layer. It sounds potentially risky though, so I am not doing that for now.
For simplicity, I am passing a reference to the Viewer Dock also to loaders for outputs that are not currently visualized in the Viewer Dock. Although at the moment it is suboptimal, it can become useful in the future, if we want to use the Viewer Dock also to interactively change some parameters in other kinds of outputs. For instance, we might want to style a map …
=> Preselect output type in Data Viewer when hcurves or uhs are loaded

svir/dialogs/load_hcurves_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_uhs_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/irmt.py
and pre-select the Data Viewer's output type accordingly.
The solution implemented in https://github.com/gem/oq-irmt-qgis/pull/245 was sub-optimal. Now I've found out how to save a custom property for a layer, so I can associate each layer with its type. Therefore, when the user selects a different layer, the plugin automatically selects the corresponding output type in the Data Viewer.
=> Use a customProperty to store the output_type of a layer

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt, svir/ui/ui_drive_engine_server.ui
Fixes https://github.com/gem/oq-irmt-qgis/issues/242
When any cell of the table containing the list of oq-engine calculations is clicked, the list of outputs
corresponding to the same calculation is displayed, and the clicked row is selected and kept on focus after following refreshes of the list.
I'm also making the row numbers invisible, in both the list of calculations and the list of outputs for a calculation, in order to avoid confusion between those numbers and the job id and output id
=> Focus on the currently pointed calculation

svir/dialogs/settings_dialog.py, svir/metadata.txt, svir/utilities/utils.py
Fixes #251 
This is a workaround to a storing issue in Mac OS
=> Save color settings as rgba instead of QColor

svir/dialogs/drive_oq_engine_server_dialog.py, svir/help/source/14_driving_the_oqengine.rst, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/256
Re-clicking the row of the currently selected calculation, the row is unselected and the table ceases to scroll automatically to keep that row visible.
=> A second click on the currently selected OQ-Engine calculation, unselects it

svir/dialogs/viewer_dock.py, svir/metadata.txt
This PR fixes https://github.com/gem/oq-irmt-qgis/issues/259, that was observed while running a script by @mmpagani and that I was able to reproduce on my computer.
The problem was that the undefined output type can be an empty string, but the check was done only with respect to the case it was `None`.
=> Fix error on selecting feature for a layer with undefined output type

svir/dialogs/transformation_dialog.py, svir/help/source/07_transform_attribute.rst, svir/metadata.txt
Closes #280
When the field transformation widget is opened, if the active layer contains fields that have a parenthesis in their name, those fields will not be listed between those that can be transformed, and a warning message will be displayed, suggesting to replace the parenthesis with a square bracket.
=> Add warning about field names containing parentheses

svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py
In addition to SELECTED_CALC_ID, with this PR you can use another environmental variable (SELCTED_OTYPE) to run integration tests only for a specific output type. This is very useful for debugging.
=> Use environ variable SELECTED_OTYPE to test only a chosen output type

.travis.yml
It first checks that the required branch exists; if not it falls back to `master`.
Than checks that the `oqdata` dump is available on the `artifacts` stow; if not, it fails without wasting time in installing packages and doing stuff until the real error is caught.
It depends on https://github.com/gem/oq-engine/pull/2922
=> Multi branch support for integration tests

svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/296
I might cherry-pick this into the current "stable" version too.
=> Set MapUnit only for the size of the simple marker, avoiding markers shifting

svir/help/source/09_weighting_and_calculating.rst
=> Add descriptions and formulae of operators used to compute composite indices

svir/help/source/11_upload_project_to_platform.rst
Plugin side I found only this reference to be fixed, plus a couple of references to the main page of the website www.globalquakemodel.org that will remain as they were.
=> Update link following the release of new website

svir/dialogs/viewer_dock.py, svir/metadata.txt
The error occurred when performing this sequence of actions:
1) draw curves from a layer that uses the Data Viewer
2) select a layer that does not use the Data Viewer
3) draw curves from another layer (not the same used at number 1) that uses the Data Viewer.
I was caused by the fact that the object keeping track of the current selection was not reinitialized when switching the active layer to one that does not use the Data Viewer.
In addition to the fix, I've also made some minor changes that make the logic slightly more readable.
=> Fix a bug occurring while redrawing curves in a corner case

svir/dialogs/viewer_dock.py, svir/test/unit/test_load_oq_engine_output_as_layer.py
A previous merge (https://github.com/gem/oq-irmt-qgis/pull/311) introduced a bug: a KeyError that occurred because of a missing reinitialization of the object holding the curves for the currently selected sites, in a corner case. Now the problem should be fixed. I've also renamed a method, to make it slightly more intuitive.
=> Fix a key error exception in redrawing curves

svir/dialogs/drive_oq_engine_server_dialog.py
The output type should remain an internal code used by the plugin but not shown to the user, whereas the output display name should be the one that the user visualizes. At the moment, they are the same, but we will have more readable display names soon (see https://github.com/gem/oq-engine/issues/3032).
The effect of this change can be seen in the following screenshots:
BEFORE
AFTER
=> Hide output type from the output list (show only the display name)

svir/dialogs/settings_dialog.py
If the the user copies/pastes the url from the webui into the plugin settings, the final `/engine` has to be removed from the url. I am stripping it before saving the user settings.
=> Strip /engine from hostname in user settings

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/viewer_dock.py, svir/test/integration/test_drive_oq_engine.py, svir/utilities/shared.py
When loading the `dmg_total` output of a scenario damage calculation, the Data Viewer lets the user select one of the realizations and one of the loss types, and there is also a checkbox to exclude (or keep) the visualization of "no damage" (the number of assets that has no damage is usually much greater than the number of assets in each of the other damage states). A bar plot is shown, displaying the number of assets in each damage state, for the selected realization and loss type.
I have not implemented the export functionality for this output, because it does not look so useful, since it is possible to download a quite simple csv directly from the OQ-Engine. If required, we can implement this in another PR. Anirudh agreed it is not needed now.
NOTE: OQ-Engine side, the outputs …
=> Load the dmg_total OQ-Engine output

svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/ui/list_multiselect_mono_widget.py
The user can select a realization, a loss type and many tags (only one value per tag can be selected), and a bar chart is plotted, displaying the number of assets in each damage state. Also the "Export data" functionality is implemented.
The ListMultiSelectMonoWidget is a subclass of ListMultiSelectWidget, that enables to select only one tag value at a time. If you select another value, it is swapped with the one that was previously selected. I could have used combo boxes instead, but the current solution will make it very easy, in the future, to enable the tool to select multiple values per tag (if the engine will allow to filter by multiple values per tag).
Error bars are not displayed, because the engine is currently unable to provide standard deviations for the selected data. I've …
=> Visualize scenario damage by tag

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/viewer_dock.py, svir/test/integration/test_drive_oq_engine.py, svir/utilities/shared.py
`dmg_total` is going to be excluded from the available OQ-Engine outputs, and the corresponding functionalities will be conceptually included in the `dmg_by_asset` output. Therefore, `dmg_by_asset` needs to have 2 different buttons: the first one loads the output as layer; the second one displays bar charts interrogating the OQ-Engine through the new `extract` API. Before this PR, the plugin assumed that each engine output could be read in only one way. I changed the logic to obtain, from one single output type, also a modified version (e.g. from `dmg_by_asset`, also a `dmg_by_asset_show`) that can be handled separately.
=> Use 2 buttons to load the same output type in different ways

svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/ui/list_multiselect_mono_widget.py, svir/ui/ui_viewer_dock.ui, svir/utilities/shared.py
A second button ("Aggregate") is added for OQ-Engine outputs of type losses_by_asset.
In the Data Viewer, it is possible to select the loss type and a set of tags.
Only for one tag name, it is possible to select a `*` tag value, meaning that losses have to be aggregated for each tag value separately. It is also possible to select a single tag value for multiple tag names.
The result is a table in which each column corresponds to one of the available gsims, and there are 3 possible cases:
1. if only one tag name is selected, and value `*` is chosen, each row corresponds to one of the tag values for that tag name
2. if many tag names are selected, with a single value for each, the table will contain a single row, showing the aggregated losses for that combination
3. If many tag names are …
=> Visualize aggregated losses_by_asset

svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/metadata.txt
As requested by Cata, layers for gmfs should not be named `scenario_damage_gmfs_rlz-RLZ_eid-EID`, but, more generically, `scenario_gmfs_rlz-RLZ_eid-EID` (which is good also for `scenario_risk`)
=> Use the same layer name for scenario_risk and scenario_damage

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt
Referring to https://github.com/gem/oq-irmt-qgis/issues/326:
1) there was a corner case in which it looked like some outputs were not displayed: it was because the Data Viewer can be hidden by the user. With this change, whenever a OQ-Engine output is loaded, the data viewer is automatically set visible, so the user can immediately notice that something has actually happened after pressing the button to load the output
2) Cata believes the label "Load npz as layer" can sound a little confusing to a user who has no idea of what a npz is. Therefore, we agreed to change the label into the simpler "Load layer"
=> Minor GUI improvements

svir/dialogs/load_output_as_layer_dialog.py
Cata pointed out that, otherwise, the label showing the number of sites could be wrongly interpreted as the label describing the dropdown menu with the list of realizations.
=> Add 'Realization' label above the corresponding dropdown

svir/dialogs/settings_dialog.py
The [`rstrip('/engine')` method](https://github.com/gem/oq-irmt-qgis/blob/v2.8.0/svir/dialogs/settings_dialog.py#L162-L163) removes all of the characters in the string '/engine' from the end of the entered hostname. This can result in the following unintended behavior:
```py
>>> 'https://wilson.openquake.org/engine'.strip().rstrip('/').rstrip('/engine')
'https://wilson.openquake.or'
```
This patch fixes the unintended stripping of extra characters from the engine hostname described above.
=> Fix unintended stripping of the engine hostname

svir/dialogs/recovery_modeling_dialog.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/344
A recent change added the `point_attrs_dict`, keeping a mapping between the original field names in the layer containing dmg_by_asset points and the possibly laundered names obtained after aggregating those points by zones. Afterwards, that dict is used by the method that calculates recovery curves.
In case points are not aggregated by zone, before this PR there was an attempt to use the dict while it was not declared. With this change I am declaring the dict where needed, mapping the original field names with themselves (since they remained unchanged).
=> Fix missing declaration of a dict happening in batch recovery not aggregating by zone

svir/dialogs/viewer_dock.py
When a layer is saved (i.e. as a GeoPackage or a Shapefile) a column 'fid' is added to the attribute table.
This is breaking the plugin when trying to plot curves because a `split('_')` is performed and a `key` which does not exists is then retrieved.
Whit this PR we are skipping operations on the `fid` field if it does exits.
Up to you @ptormene if you want to backport the fix to 2.8.
=> Skip any operation on the 'fid' field

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
In some corner cases, it was possible to press buttons pointing to elements that had been removed, causing exceptions. I fixed those cases. I also made some minor refactoring.
=> When a OQ-Engine calculation is removed, clear corresponding GUI elements

svir/calculations/process_layer.py, svir/irmt.py, svir/test/unit/test_load_oq_engine_output_as_layer.py
A couple of signals were not disconnected while unloading the plugin. There's a remote probability that it might be the cause of some issues while upgrading the plugin.
Meanwhile, I've also fixed a couple of tests, that still cause a segmentation fault (so they are still skipped) but that now pass if unskipped. Unfortunately, I still haven't found a way to avoid the segfault.
=> Remove connects while unloading plugin and partially fix some skipped tests

svir/help/source/00_installation.rst
- Packages are better known as python2-something
- Qt4 backend needs to be explicit
=> Update dnf packages list in doc

svir/dialogs/download_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/recovery_settings_dialog.py, svir/dialogs/settings_dialog.py, svir/dialogs/viewer_dock.py, svir/ui/list_multiselect_widget.py, svir/utilities/sldadapter.py
The qgis wrapper that imports from PyQt4 or PyQt5 is working in most cases also on Mac OS, except when importing Qt.
As a workaround, I'm rolling back to how it was in the previous stable version of the plugin:
`from PyQt4 import Qt` 
instad of 
`from qgis.PyQt import Qt`
=> Workaround to fix importing Qt on Mac OS

svir/irmt.py
The dialog was correctly initialized, but it was not shown because the `show` parameter was unexpectedly set to False (an additional parameter was passed by the signal triggered by the button).
=> Fix showing the dialog that drives the oq-engine

svir/irmt.py
The glossary will be opened automatically from TaxtWEB.
Cata believes it's useless to have an additional button to explicitly open the taxonomy.
=> Remove button to open the glossary for GEM taxonomy

svir/dialogs/download_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/recovery_settings_dialog.py, svir/dialogs/settings_dialog.py, svir/dialogs/viewer_dock.py, svir/ui/list_multiselect_widget.py, svir/utilities/sldadapter.py
A Qt module exists also under qgis.PyQt and it is similar to the one contained in qgis.PyQt.QtCore, but:
1) in some cases it works on Ubuntu and not on macOS
2) it does not have exactly the same properties that are in the one under QtCore
Using always the Qt module contained in QtCore, I've tested it on Ubuntu and on macOS, and it works. Therefore, I'm removing the ugly workaround introduced in https://github.com/gem/oq-irmt-qgis/pull/363
=> Import Qt module from qgis.PyQt.QtCore instead of from qgis.PyQt

svir/dialogs/standalone_app_dialog.py
By default, Qt widgets can not be minimized. This PR adds the possibility to minimize all the embedded OQ standalone applications.
=> Enable minimizing windows of standalone oq applications

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_dmg_by_asset_as_layer_dialog.py, svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/load_hcurves_as_layer_dialog.py, svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_losses_by_asset_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/dialogs/load_uhs_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py, svir/test/unit/test_load_oq_engine_output_as_layer.py, svir/utilities/utils.py
Layers for hazard maps, hazard curves and uniform hazard spectra were previously obtained downloading npz files and loading data from them. With this change, the "extract" api is used instead. This is in the direction of using the "extract" api both for risk and hazard engine outputs. In future PRs we plan to do the same for other outputs that still use the exported npz files.
=> Extract hazard

svir/dialogs/standalone_app_dialog.py, svir/metadata.txt
The plugin attempted to load a default from a variable that does not exist anymore (after the introduction of connection profiles), so the standalone applications could not set the hostname correctly.
Therefore, in v2.9.3 (just released), if you try to open IPT or TaxtWEB, the plugin breaks.
I propose to publish v2.9.4 right after this quickfix.
=> Fixed retrieval of the engine server hostname from settings

svir/irmt.py
Those outputs can not be loaded from npz files anymore, but I forgot to remove the corresponding menu items (that became broken after that change). Now the only way to load those outputs is through the dialog that drives the OQ-Engine.
=> Remove menu items to load hmaps hcurves and uhs from npz

svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt
1. also layers that have nothing to do with the Data Viewer will contain the calc_id as a custom property, that can be retrieved through the Python Console (calc_id = iface.activeLayer().customProperty('calc_id')). Perhaps I should also provide a more intuitive way for the user to get the calc_id (for instance, a contextual menu, or I could add it to the layer name before the investigation time)
2. while exporting curves with the Data Viewer, the exported file name will contain the calc_id (fixes https://github.com/gem/oq-irmt-qgis/issues/320)
=> Add calc_id to layers as customProperty and put it in exported filename

.travis.yml, docker/Dockerfile, svir/test/integration/test_drive_oq_engine.py
Recycle the work done in #111 to run tests in Travis via Docker: this allow us to use Ubuntu 16.04 and avoid issues with integration tests (now it's possible to revert #402 ).
=> Use Docker for running tests in Travis

svir/dialogs/viewer_dock.py
Improves the situation highlighted in https://github.com/gem/oq-irmt-qgis/issues/423
The problem occurs when we clean up the viewer dock in order to replace the current widgets (and their contents) with those that are related to another kind of OQ-Engine output. While cleaning up things, it might occur that we attempt to clear a combo box that has already been deleted. In this case, it's good to log a warning, but we should not bother the user too much, so we can avoid displaying the message also in the QGIS message bar.
=> Log as warning (no msg bar) if cleaning an already deleted combo

svir/dialogs/viewer_dock.py
Before this change, I was saving the selection associated to each tag, regardless from the fact the tag is currently selected or not. It was reasonable, because this way you could deselect one tag and then reselect it, without losing the association between that tag and the corresponding selected values. This caused a problem, though, when the `*` is selected for one tag, and then the user deselects that tag and wants to select the `*` for a different tag. Since it's currently forbidden to have the `*` selected for multiple tags, it was impossible to do the selection, unless you re-select the previous tag, remove the `*`, and then apply the `*` to the new tag. This happened to Cata, and she couldn't intuitively find out how to do the trick. Therefore, I'm changing the approach here, …
=> Deselect tag values for tags that are unselected

svir/dialogs/viewer_dock.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/427
I've also improved the table (and the corresponding exported csv) for aggregate losses, in case `*` is selected for a tag. Instead of writing in each line something like `taxonomy=Wood`, I'm writing just `Wood`. In the header of the csv, instead of writing `tag`, I'm writing the tag name (e.g. `taxonomy`).
=> Reduce duplication visualizing losses by asset

svir/calculations/aggregate_loss_by_zone.py, svir/calculations/calculate_utils.py, svir/calculations/process_layer.py, svir/dialogs/load_dmg_by_asset_as_layer_dialog.py, svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/load_hcurves_as_layer_dialog.py, svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_losses_by_asset_as_layer_dialog.py, svir/dialogs/load_uhs_as_layer_dialog.py, svir/utilities/utils.py
Since QGIS 2.12, a context manager to edit a layer was added: http://www.opengis.ch/2015/08/12/with-edit-layer/
I was using a very similar context manager (LayerEditingManager) that also optionally logged messages like "BEGIN doing something... END doing something" but that missed doing a roll-back in case of failure. With this PR I am removing my own context manager, replacing all occurrences with the QGIS native one.
=> Substitute LayerEditingManager with the native QGIS edit manager

svir/irmt.py
Fix https://github.com/gem/oq-irmt-qgis/issues/448
This is the only oq-engine output that still had a menu item to load it directly from file. We want to change the loader to use the extract api instead of loading from csv, so it would have been removed anyway.
=> Disable the broken menu option to load ruptures from file

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
This should reduce the loading time by about one half. This can be crucial, especially for big outputs loaded from a cluster. I should make a new release with this fix, as soon as possible.
This does NOT reduce the duration of integration tests, because in the tests I was already calling the loaders (that perform the extract) without downloading the npz in advance.
=> Avoid useless downloading of npz (extracted anyway afterwards)

svir/test/integration/test_drive_oq_engine.py
Setting a threshold of 10 seconds (listing outputs that took more than 10 seconds to load), the outcome is the following:
```python
Some loaders took longer than 10 seconds:
{'calc_id': 14, 'calc_description': 'Classical PSHA with Characteristic Fault Source defined by Complex Fault Geometry.', 'output_type': 'hcurves', 'loading_time': 103.69501376152039}
{'calc_id': 13, 'calc_description': 'Example Classical PSHA using Characteristic Fault Source with Simple Fault Geometry', 'output_type': 'hcurves', 'loading_time': 97.49299550056458}
{'calc_id': 14, 'calc_description': 'Classical PSHA with Characteristic Fault Source defined by Complex Fault Geometry.', 'output_type': 'uhs', 'loading_time': 71.41788148880005}
{'calc_id': 13, 'calc_description': 'Example Classical PSHA using …
```
=> At the end of integration tests, list outputs that took long to load

svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt
After https://github.com/gem/oq-irmt-qgis/pull/488 and https://github.com/gem/oq-irmt-qgis/pull/489, the user became unable to load hmaps altogether in a single layer (one layer per realization or statistic).
In this PR I am adding another checkbox, to follow the original workflow. Therefore, the user will be able to choose the preferred approach.
=> Add possibility to load hmaps in one layer per realization (or per statistic)

svir/dialogs/load_hmaps_as_layer_dialog.py
This is just a quick fix to clarify something in the GUI, that was a little confusing.
If you choose to download hazard maps using one multi-column layer per realization, IMT and POE can still be selected, and the chosen ones are used to style the layer automatically. In this case, I am adding "used for styling" to the labels on top of the corresponding drop-down menus. This way it becomes clearer that, whatever you choose, all the IMTs and all the POEs are loaded in the layer, but the default styling is done using the chosen ones.
=> Loading single-layer hmaps, specify in labels what's chosen for styling

svir/dialogs/viewer_dock.py, svir/metadata.txt
Without casting to float, plots looked fine for almost every IMTs (luckily), except PGV (see figure).
In the rare case of Modified Mercalli Intensity Scale, in which IMLs are not numeric, the original values will be kept. The OQ-Engine demos do not include any example using that scale.
=> Cast IMLs to float if possible (fix plotting of IMT=PGV)

svir/websocket/ipt_app.py
Check if a folder is relativized properly to its parent dir without move outside the parent dir tree.
=> add method to accept a relative path as legal for web apps

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/settings_dialog.py, svir/irmt.py, svir/metadata.txt
1. When saving plugin settings, any dialog driving the oq-engine is reset, thus avoiding issues with old dialogs pointing to resources that are on a server that is no longer available (fixes https://github.com/gem/oq-irmt-qgis/issues/510)
2. When the connection with the oq-engine server is lost, the plugin attempts to reconnect 3 times before displaying an error and loading the settings dialog (fixes https://github.com/gem/oq-irmt-qgis/issues/503)
=> Better handling of the connection to the oq-engine server

svir/websocket/ipt_app.py, svir/websocket/web_app.py
- add `app-msg` layer to `cmd-msg` returned by synchronous methods [(here a schematic description)](https://github.com/gem/oq-irmt-qgis/blob/qgis3-ss-complete-fix-delegate-dl-refact/svir/websocket/ipt_app.py#L634).
- OS independent (posix style) file paths notation to and from web-application API.
- add `realpath` attribute to msg returned at the end of `delegate_download` method.
=> Qgis3 ss complete fix delegate dl refact

README.md, svir/help/source/00_installation.rst, svir/metadata.txt
Actually, with @raoanirudh, we tested the workaround on matplotlib v2.2.2, but I believe also v2.2.3 would work fine as well. We should double-check it though.
=> Add instructions working around a bug in matplotlib 3.0.0 for macOS

svir/dialogs/viewer_dock.py, svir/metadata.txt
It looks like the format of the extracted data changed engine-side. With these little changes, it seems to work properly.
=> Fix aggregate avg_losses-stats

svir/test/qgis_interface.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/527
While running tests, showing an actual message bar is useless, so we can use a mock as a workaround to avoid that annoying warning. I couldn't find any proper way to fix the fact that qgis is not finding that svg.
Even using a mock instead of the actual message bar, a single warning still appears on top of the log, but it's unobtrusive (the other dozens of obtrusive occurrences disappeared).
=> Mock messageBar in tests, to avoid warning about a missing svg file

svir/metadata.txt, svir/tasks/extract_npz_task.py, svir/utilities/utils.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/525
While fixing that issue, I noticed a couple of bugs, that I've fixed too:
1. the log verbosity was not getting the information from the right variable, therefore it was always set to WARNING, regardless from what the user selected
2. the task that calls the extract api was ignoring parameters, so the outputs were wrong. I can't understand why I did not spot it before.
=> Fix call to the extract api and log as info both url and params

svir/metadata.txt, svir/tasks/extract_npz_task.py
It works for the case described by Daniele, with a permission error. I haven't tried other cases, but I am fairly confident it should work in most cases.
Fixes https://github.com/gem/oq-irmt-qgis/issues/535
=> When an OQ-Engine output can't be extracted, log the reason

svir/tasks/download_oq_output_task.py, svir/tasks/extract_npz_task.py, svir/utilities/utils.py
This should leverage the `log_msg` function that was already called, also printing to stderr in this specific case, instead of just logging to the qgis log and to the qgis message bar.
Let's see how it behaves on Travis.
=> Force printing also to stderr while logging from ExtractNpzTask

svir/calculations/calculate_utils.py, svir/dialogs/download_layer_dialog.py, svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_basic_csv_as_layer_dialog.py, svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/dialogs/projects_manager_dialog.py, svir/dialogs/recovery_settings_dialog.py, svir/dialogs/settings_dialog.py, svir/dialogs/transformation_dialog.py, svir/dialogs/upload_dialog.py, svir/dialogs/upload_settings_dialog.py, svir/dialogs/viewer_dock.py, svir/dialogs/weight_data_dialog.py, svir/irmt.py, svir/metadata.txt, svir/utilities/utils.py
This is an improvement to the utility we use in the plugin to communicate with the user.
In case `log_msg` is called passing also an exception as parameter, the user will be able to visualize the traceback by clicking on a button that will appear in the messageBar. Therefore the messageBar will display the short version of the error message, but it will be easy to visualize the full error. 
To see how it works, you can attempt to drive the engine while the engine server is not running.
=> Show traceback

svir/dialogs/drive_oq_engine_server_dialog.py, svir/test/integration/test_drive_oq_engine.py
Some functionalities of the dialog that drives the Oq-Engine were re-implemented in the integration tests instead of leveraging the dialog itself.
I still need to fix the cases in which an output is downloaded from the Oq-Engine, for which we should test the actual downloader task. It was tricky and I couldn't fix that quickly, so I will postpone it to a separate PR.
=> Let integration tests reuse more code from the plugin instead of reimplementing parts of it

svir/dialogs/drive_oq_engine_server_dialog.py
This way, for the latest demo, it's possible to load (successfully) all outputs except the "Show" ones, that were broken.
=> Disable 'Show' buttons if calculation_mode == 'ebrisk'

svir/irmt.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/464
Now it should be possible to reload the plugin using the plugin reloader tool, without raising exceptions.
The change is just a couple of lines of code, but it makes a big difference, because I can avoid to keep closing/opening qgis whenever I change code in the plugin.
=> Fix unloading plugin menu

svir/dialogs/viewer_dock.py, svir/metadata.txt
csv.writer was already producing data with the \r\n separator, but the problem was in the additional lines on top of the files, prepended by a #, that contain metadata such as the creation time, the engine and plugin version and some other scientific data.
Now I am using \r\n as line separator also while writing those headlines.
Fixes https://github.com/gem/oq-irmt-qgis/issues/561
=> Fix newline separators in csv files exported by the Data Viewer

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt, svir/ui/ui_drive_engine_server.ui
Fixes https://github.com/gem/oq-irmt-qgis/issues/559
I removed the automatic redirection to the plugin settings.
While the connection is not working, the GUI is temporarily disabled and the plugin attempts to reconnect to the engine server for 3 times. If the server remains unreachable during those attempts, the GUI remains disabled, but there is an additional "Reconnect" button to actively attempt a new reconnection.
=> Improve management of failed connection with the engine server

svir/dialogs/load_output_as_layer_dialog.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/557
Via pdb I checked that it sets reasonable levels, but it looks like it is working on a copy of the legend symbol items, so the original renderer remains unchanged.
I tried to do something like `renderer.setLegendSymbolItem`, but I did not understand how to pass a proper key parameter to that function.
=> Set incremental symbol levels

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
@CatalinaYepes had problems downloading the asset_risk output as csv, but I was surprised that the plugin attempted to download it instead of just using the extract api. In fact, there were two bugs: one in the engine (that could not export the csv) and one in the plugin (that was uselessly downloading the csv before loading the actual data through the export api).
In this part of the code that I fixed the logic is a bit tricky, so I should probably refactor it a bit in another PR. For now, this solves the issue.
PS: considering that the asset_risk csv file is sometimes quite big, avoiding to download it should make the plugin noticeably faster while displaying the dialog to load that output.
=> Avoid downloading asset_risk unused csv output

svir/dialogs/load_asset_risk_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/ui/ui_load_output_as_layer.ui
Fixes https://github.com/gem/oq-irmt-qgis/issues/578
I thought about doing the same also for the "Aggregate by zone" groupbox, but it is a little more tricky, so I decided to keep it as it is, at least for the moment.
=> Collapse taxonomies_gbx and tag_gbx when unchecked and adapt dialog size

svir/dialogs/drive_oq_engine_server_dialog.py, svir/help/source/04_irmt_settings.rst, svir/help/source/14_driving_the_oqengine.rst, svir/irmt.py
This minor change should make it more intuitive for users to understand that the engine server starts when you "run the webui".
=> Add (WebUI) wherever explaining things about the OQ-Engine server

svir/dialogs/show_console_dialog.py, svir/irmt.py, svir/metadata.txt
A step forward with respect to https://github.com/gem/oq-irmt-qgis/issues/585
=> Stop any running timer before unloading the plugin

svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/metadata.txt
This PR fixes two problems:
1. there was a redundant checkbox to load only selected items, which functionality overlapped with that provided by the checkbox used to select one or all realizations. In this context we don't need to avoid selecting all IMTs, so it's pointless to keep another checkbox to force selecting only one IMT.
2. when choosing to load one layer per GMPE, multiple layers were created, but all containing data corresponding to the GMPE that was currently selected in the dropdown menu.
We still don't have a way to display an average GMF, because this is not provided by the OQ-Engine. The hazard scientists are discussing about it, but for now we will just display the separate GMFs corresponding to the available GMPEs.
=> Fix visualization of multiple realizations for GMFs

svir/irmt.py, svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py
This slightly simplifies the logic of integration tests, avoiding some duplication.
This change is a necessary step towards the implementation of integration tests that that will use hybridge to run OQ Engine calculations from IPT (which will require the interaction between an instance of Hybridge and an instance of Irmt)
=> Instantiate Irmt in integration tests, letting it handle its sub-dialogs

svir/dialogs/load_inputs_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py, svir/utilities/shared.py, svir/utilities/utils.py
The GUI will create a checkbox for each of the files specified in the multi_peril_csv section of the .ini file. They will be checked by default, therefore all files will be loaded as layers if the user just presses ok. Otherwise, users can unselect as many files as they prefer.
All csv files that contain an 'intensity' column will be styled with respect to it.
All files that contain a 'wkt' column will be read using that column to retrieve the geometry. In order to be more flexible, I am also accepting columns like 'geom', 'the_geom' or 'geometry' (case insensitive).
=> Allow reading geometries from multi-peril input files

svir/utilities/shared.py
Companion of https://github.com/gem/oq-engine/pull/4882
Besides some code re-alignment, the only actual change is commenting out the loader for `agg_curves-stats`, that is the only one that uses `extract/agg_curves/loss_type`
=> Disable whatever calls extract/agg_curves

svir/dialogs/load_dmg_by_asset_as_layer_dialog.py, svir/dialogs/load_losses_by_asset_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/599
Taxonomies are returned by extract/losses_by_asset as bytes instead of strings. I was already decoding them as utf8 to be able to populate the corresponding dropdown menu. The problem was that I was not re-encoding the user-selected one as utf8 before comparing it with the data for filtering in `group_by_site`, therefore the filter always returned no records and the output layer was completely empty.
If we can assume that all bytes coming from the engine can be decoded as utf8, this fix is fine. Otherwise, perhaps it would be safer to store taxonomies as strings in the engine datastore.
=> Encode taxonomy in utf8, to avoid loading empty losses_by_asset or dmg_by_asset layers

scripts/run_integration_tests.sh, svir/dialogs/drive_oq_engine_server_dialog.py, svir/tasks/extract_npz_task.py, svir/test/integration/test_drive_oq_engine.py, svir/utilities/shared.py, svir/utilities/utils.py
Thanks to the QGIS docker, we can now remove every mocked objects from integration tests.
I've also noticed that in many tests I was selecting all the features and drawing all the corresponding curves, whereas it is sufficient to draw just a couple. This change made the tests for many output loaders much faster. In fact, it reduced the execution of integration tests from 658.462s to 236.349s, and we don't have any warnings about loaders taking more than 10 seconds to run.
I changed the way loaders are tested. Instead of running a single test with a big loop, trying to load all the outputs of all the available calculations, I have now one test for each loader, looping on all the available calculations and loading a specific output type for all of them. Each test produces its own summary, …
=> Major improvements in integration tests

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
(e.g. Aggregate Asset Losses -> agg_losses-rlzs)
In the past, we decided to avoid displaying such information in the table, keeping the visualized data simpler and cleaner. However, this is visualized in the WebUI, and it can be useful in some cases.
I decided to implement this hybrid approach, to allow users to easily obtain the information by pointing the mouse to the output name and visualizing the tooltip, so the table remains as simple and clean as before.
=> Hovering on the name of an engine calc output, a tooltip displays the output type and its size

scripts/run_integration_tests.sh, svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py
I've added the possibility to use an env variable to run tests only for a specific calculation id.
For losses_by_asset, I am testing loading alternatively: 'All' taxonomies, or the first other taxonomy that is found (displaying the name of the taxonomy in the output of the test).
TODO:
=> Improvements to the integration tests

svir/dialogs/viewer_dock.py, svir/ui/ui_viewer_dock.ui
I made a couple of changes:
1. The dropdown menu to select the output type in the Data Viewer dock will remain always disabled. Now custom properties are added to the layers, specifying the layer output type. When you select a layer, it causes the automatic selection of the correct output type in the data viewer. Changing that selection manually is in general wrong, and in most cases it causes some exception to occur, so I decided to prevent it from happening accidentally.
(fixes https://github.com/gem/oq-irmt-qgis/issues/605)
2. The checkbox to style the plot in black&white was on top of the widget, but it makes more sense to keep it on the bottom, close to the plotting area, so I moved it there.
We might consider removing the dropdown menu and replacing it with a label, because now the …
=> Minor improvements to the Data Viewer dock window

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/611
After selecting the input files, a dialog is displayed, containing a combobox from which the user can select one of the '.ini' files that are available in the list of the input files.
If the user presses "cancel", the engine will pick a ini file by default. Otherwise the chosen file will be used.
=> Enable the user to select which ini file will be used in a OQ-Engine calculation

svir/dialogs/viewer_dock.py, svir/metadata.txt
This way the user has all the necessary information to be able to re-calculate a recovery curve.
Fixes https://github.com/gem/oq-irmt-qgis/issues/612
=> Add to exported recovery curves info about approach, n_simulations, assets

svir/metadata.txt, svir/utilities/utils.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/626
For some reason, the following two lines give different results:
```python 
settings.value('irmt/style_mode', DEFAULT_SETTINGS['style_mode'], type=int))
int(settings.value('irmt/style_mode', DEFAULT_SETTINGS['style_mode'])))
```
The first one returns a negative value, different with respect to the number written as string in the setting. In MacOS, such negative number could not be accepted while doing
`color_from = QColor().fromRgba(color_from_rgba)`, whereas it was accepted in Linux.
=> Fix an issue saving colors to QSettings

svir/dialogs/drive_oq_engine_server_dialog.py, svir/test/integration/test_drive_oq_engine.py
I was using a fragile approach to run the first found risk demo, but recently something changed and the test was not running as expected anymore. Another problem was that, in case of multiple ini files, the plugin now asks the user which one to use for the calculation, which would put the tests on hold, waiting for a response from the user. Now, while running tests, I use instead the original approach to let the engine guess which ini file to use from those that are available.
=> Use ScenarioDamage risk test in integration tests

svir/dialogs/load_basic_csv_as_layer_dialog.py, svir/metadata.txt
Partially addressing https://github.com/gem/oq-irmt-qgis/issues/635
=> Load outputs as tables from csv with a single click

svir/dialogs/viewer_dock.py, svir/ui/multi_select_combo_box.py
When a tag name is selected, a corresponding multiselector for its values is added to the GUI if needed, and when it is unchecked, the corresponding multiselector is removed if present.
In case we want to use a simple selector that looks like a normal combobox, we can use a modified version of the MultiSelectComboBox that is compatible with the API of QComboBox.
=> Chained multiselect

svir/dialogs/load_basic_csv_as_layer_dialog.py, svir/utilities/utils.py
This should fix the headers in tables imported from csv, now that the OQ-Engine outputs contain commented lines on top.
=> In import_layer_from_csv skip commented head lines

svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/utilities/shared.py
I have also fixed a wrong order in indices of agg_curves-rlzs.
For some reason, agg_curves-stats (while it was disabled) was meant to be used also filtering data by tags, whereas agg_curves-rlzs was not. I removed such filtering because it was not working and the shape of the data was incompatible with that. However, I might have broken the visualization of other outputs that might have had the right shape for filtering by tag.
=> Fix visualization of agg_curves-stats

svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/irmt.py, svir/metadata.txt, svir/utilities/shared.py
We are also connecting some signals (e.g. currentLayerChanged) after iface.initializationCompleted is emitted.
On currentLayerChanged, if the current layer is one of those that use a cross symbol, then the selected features color becomes red. Otherwise, the original color is used (that by default is yellow)
Also fixes https://github.com/gem/oq-irmt-qgis/issues/614
=> Set selected features color depending on the output type

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/658
As soon as the calculation starts, the list of outputs is cleaned up. When the calculation is complete, its list of outputs is automatically loaded.
=> Preselect a running calculation if it is successfully started

svir/utilities/utils.py
Before this PR, error messages would be entirely displayed in the qgis message bar if they were below a threshold length of 200 characters. For longer messages, a button pointed to the full message.
@CatalinaYepes requested to reduce this threshold. A threshold of 120 characters looks good to me (it is approximately one line on my screen)
=> Reduce the maximum length of error messages

svir/dialogs/drive_oq_engine_server_dialog.py
Recently (in https://github.com/gem/oq-irmt-qgis/pull/560) I introduced a little bug: after reconnecting to the engine server, all buttons in the GUI were re-enabled, including those that are related to a specific calculation (those used to download the datastore or to visualize the parameters of the calculation).
Here I am checking that those buttons are re-enabled only if a calculation is currently selected.
=> Fix enabling/disabling buttons that depend on current calculation

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Moving the cursor through the list of available OQ-Engine calculations, the calculation corresponding to the highlighted cell is automatically selected and its list of outputs is displayed.
Fixes https://github.com/gem/oq-irmt-qgis/issues/382
=> Select current OQ-Engine calculation also while moving across the list with arrow keys

svir/dialogs/drive_oq_engine_server_dialog.py, svir/test/integration/test_drive_oq_engine.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/688
In master I was keeping this skipped because it was causing some issues while running the risk part of the calculation and attempting to remove both calculations afterwards. We can see if we still have those connection issues and if meanwhile everything is solved engine-side about removing calculations.
=> Unskip test running risk on top of hazard, then removing both calculations

svir/dialogs/drive_oq_engine_server_dialog.py
I am also handling some additional error types
=> Avoid to print the traceback of connection errors in integration tests

svir/test/integration/test_drive_oq_engine.py
I noticed that in some cases it is not clear from the log that a calculation was completed successfully, so I am adding some prints to clearly state when a calculation is complete, when it failed, when it is removed afterwards.
I've also noticed that in some very rare cases all integration tests fail from the beginning while attempting to retrieve the list of calculations. I could add a loop to retry until a timeout is reached, but it is tricky stuff that I prefer to avoid for now.
=> In integration tests, make sure calculations are completed correctly

svir/dialogs/load_output_as_layer_dialog.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/703
Exploring one by one the steps done by the loader for hcurves (that resizes the dialog correctly) I found out that the line that actually modified the behavior was just changing the text of a label. I tried doing the same in the dialog for ruptures, and I found out that what changes the adjustSize behavior is the fact that a label is modified after adding it to the layout where it belongs. This is a very bizarre behavior that I am unable to explain and that should be further investigated. I've added a note in the code about this.
=> Hack to fix resizing the dialog loading ruptures

scripts/make_doc.sh, scripts/run_integration_tests.sh, scripts/run_unit_tests.sh, svir/calculations/calculate_utils.py, svir/dialogs/load_asset_risk_as_layer_dialog.py, svir/dialogs/load_dmg_by_asset_as_layer_dialog.py, svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/load_hcurves_as_layer_dialog.py, svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_losses_by_asset_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/dialogs/load_uhs_as_layer_dialog.py, svir/irmt.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/712
While doing this I made also some refactoring to reduce duplication in methods that add attributes to layers and methods that retrieve field names and types.
I also removed QgsExpression.quotedColumnRef where it was not needed. I am still using it in expressions for rule-based classification, to properly quote field names inside the expression, but it is not needed otherwise.
I made changes to a dozen of files, so I have to be careful that everything still works properly.
In some cases I am assuming that fields are numeric, but I still have to double-check that it is true in those cases.
=> Set field data types correctly while loading oq-engine outputs

.travis.yml, svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py
and enable their visualization for event-based calculations
TODO:
=> Prefilter ground motion fields by event id

svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/metadata.txt, svir/utilities/utils.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/715
Currently the oq-engine produces ruptures as polygons, but a change like https://github.com/gem/oq-engine/pull/5383 would allow to use lines instead of dengenerate polygons when needed.
With this PR I am creating different layers, one for each geometry type. It would also accept geometries other geometry types that are currently not produced by the oq-engine: point, multipoint, multilinestring or multipolygon.
If ruptures of multiple geometry types are found, layers are added to a group and zooming is done to the group extent.
Open issues:
- layer styles are not consistent across layers, so for instance the same TRT could be represented with different colors in layers corresponding to different geometry types (also because the number of …
=> Load ruptures as separate layers with proper geometry types

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt
Without this change, it would have been impossible to select all the input files for some calculations that include files in subdirectories.
I first tried a different approach with respect to the one implemented here, which consisted in modifying the file selector widget to accept the selection of both files and directories. However, it was tricky and a little confusing, so I changed the approach: when the user presses "run calculation", they have first to choose if they prefer to select input data from a directory or from a zip file. In case a directory is selected, also subdirectories are zipped together and sent to the engine.
=> Select input files from zip or directory (and include subdirectories)

svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt
While making a recent change I did not notice I was modifying a dict while looping on its keys, which caused the loop to make an undesired additional iteration. As a consequence, an empty field with a strange name was added to the layer.
Fixes https://github.com/gem/oq-irmt-qgis/issues/730
Fixes https://github.com/gem/oq-irmt-qgis/issues/728
=> Fix loading GMFs

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_asset_risk_as_layer_dialog.py, svir/dialogs/load_basic_csv_as_layer_dialog.py, svir/dialogs/load_csv_as_layer_dialog.py, svir/dialogs/load_dmg_by_asset_as_layer_dialog.py, svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/load_hcurves_as_layer_dialog.py, svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_losses_by_asset_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/dialogs/load_uhs_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/734
Most of https://github.com/gem/oq-irmt-qgis/issues/731 should be ok after the changes made in this PR and in https://github.com/gem/oq-irmt-qgis/pull/733
=> Fix gmf layer names; display gmpe ranges when selecting event id

svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt
When loading hmaps, instead of creating one different layer for each combination of realization/statistic, imt and poe, or to create one layer for each realization or statistic, we can now produce a single layer storing all maps together. Instead of creating a single style, only for the combination of items chosen from the GUI, we create now a style for each layer field. This way, from the OQ-GeoViewer, it will be possible to load one single layer and to select the desired style to display the map accordingly.
=> Load hmaps in a single layer

scripts/run_integration_tests.sh, svir/how_to_run_tests.txt, svir/test/integration/test_drive_oq_engine.py
It was already possible to run tests for only one calc id, but it was not skipping some other tests, e.g. testing running a new calculation, etc.
=> Add possibility to run integration test for only one output type and/or for only one calc id

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/utilities/shared.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/756
This also fixes renaming an oq-engine output as it was recently renamed engine-side (losses_by_event -> agg_loss_table)
=> Hack to fix wrong resizing of vertical headers in viewer dock

.github/workflows/qgis_383.yml
Attempting to fix the behavior of CI both for PRs and for daily runs.
To fix:
=> Add check for 'skip CI'; correctly set branches for IRMT and Engine

svir/dialogs/drive_oq_engine_server_dialog.py
Avoiding to remove items that were already cleaned up. Fixes an exception on loading volcano demo.
=> Slightly safer way to remove download_task or dlg after completion

svir/dialogs/load_damages_rlzs_as_layer_dialog.py, svir/metadata.txt
Some strings were forced to be stored into fields defined as float. QGIS 3.10 was not complaining about it, but it caused some subtle side-effects; QGIS 3.16 instead raises an exception in that case.
=> Fix field types loading Asset Damage Distribution

svir/recovery_modeling/recovery_modeling.py, svir/test/integration/test_drive_oq_engine.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/738
Recovery modeling tests were skipped because engine-side fields containing probabilities were removed the `_mean` suffix and because some textual fields were wrongly defined as numeric (see https://github.com/gem/oq-irmt-qgis/pull/773).
I am assuming now that if no fields are found with _mean suffix, then all fields are pre-selected as those containing probabilities (the user can unselect them if that's incorrect).
=> Restore integration tests for recovery modeling

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py, svir/utilities/shared.py
Companion of https://github.com/gem/oq-engine/pull/7227.
=> Replaced output `agg_losses-stats` with aggrisk

svir/irmt.py, svir/test/unit/test_calculate_indices.py, svir/thread_worker/upload_worker.py, svir/utilities/utils.py
The change between V2 and V3 seems to be all internal to QGIS, whereas V2 changed the required parameters with respect to the previous version. However, the return value seems to be in a different format, so it is more complicated than it looked like initially.
Fixes https://github.com/gem/oq-irmt-qgis/issues/784
=> Replace deprecated writeAsVectorFormatV2 -> writeAsVectorFormatV3

svir/__init__.py, svir/dialogs/viewer_dock.py, svir/irmt.py, svir/recovery_modeling/recovery_modeling.py, svir/utilities/utils.py
We already had a clear error message in case other packages were missing. We are doing the same for `Pillow`, which is never explicitly used by the plugin, but it required anyway.
=> Raise an error if Pillow is missing when loading the plugin

svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/load_uhs_as_layer_dialog.py, svir/metadata.txt
Fixes reading GMFs when 'custom-site-id' is present as first column.
=> Read 'lon' and 'lat' from 'row' using field names instead of positionally as first and second item

.github/workflows/qgis_383.yml, .github/workflows/qgis_latest.yml, .github/workflows/qgis_ltr.yml, README.md, scripts/doc_upload.sh, scripts/make_doc.sh, svir/Makefile, svir/help/source/00_installation.rst, svir/help/source/14_driving_the_oqengine.rst, svir/help/source/15_viewer_dock.rst, svir/metadata.txt
Improvements:
- the documentation is built using a docker containing all the necessary dependencies
- the version is read from metadata instead of setting an environmental variable manually
- the documentation is set as LTS or latest depending on the 'experimental' flag read from metadata
To be checked by @vot4anto:
- the docker builds the documentation setting all files as owned by root, so it's not possible to edit the pdf of the manual afterwards without updating permissions with sudo. Is there a better way to do this?
NOTE: integration tests fail because this is aligned with Engine 3.11, but tests are versus Engine master
=> Improve makefile

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_csv_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/help/source/15_viewer_dock.rst, svir/metadata.txt, svir/utilities/shared.py
Companion of some engine-side changes:
- https://github.com/gem/oq-engine/pull/8394
- https://github.com/gem/oq-engine/pull/8390
- https://github.com/gem/oq-engine/pull/8397
=> Fix visualization of OQ-Engine outputs needed for risk workshops

svir/dialogs/drive_oq_engine_server_dialog.py, svir/dialogs/load_disagg_rlzs_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py, svir/utilities/shared.py
In OQ-Engine 3.17 the `disagg` output was split into `disagg-rlzs` and `disagg-stats`. This PR uses the existing loader for `disagg` to load the current `disagg-rlzs` output.
=> Fix loader of `disagg-rlzs`, previously called `disagg`

svir/dialogs/drive_oq_engine_server_dialog.py, svir/metadata.txt, svir/test/integration/test_drive_oq_engine.py, svir/utilities/shared.py
@micheles, please note that `mean_disagg_bysrc` is actually spelled like this, but I suppose it should be `mean_disagg_by_src`. If this is something recent that does not break any external tool, perhaps we could rename it engine-side.
=> Load csv as layer also for `rates_by_src` and `mean_disagg_bysrc`

svir/test/integration/test_drive_oq_engine.py, svir/test/unit/test_calculate_indices.py, svir/test/unit/test_dumb.py, svir/test/unit/test_init.py, svir/test/unit/test_irmt.py, svir/test/unit/test_loss_aggreagation.py, svir/test/unit/test_multi_select_combo_box.py, svir/test/unit/test_process_layer.py, svir/test/unit/test_qgis_environment.py, svir/test/unit/test_transformations.py, svir/test/unit/test_translations.py
...and use super().setUp() or similar when overriding methods of qgis.testing.unittest
It fixes the `AttributeError: type object 'MultiSelectComboBoxMonoTestCase' has no attribute 'report'` happening using the latest qgis docker image.
=> Import qgis.testing.unittest instead of importing the standard unittest

svir/dialogs/recovery_modeling_dialog.py, svir/dialogs/viewer_dock.py, svir/recovery_modeling/recovery_modeling.py, svir/test/integration/test_drive_oq_engine.py, svir/utilities/shared.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/834
The new Infrastructure Risk Demos produce damages_rlzs that are used in integration tests for recovery modeling. The Water Supply Demo has a number of damages states compatible with the default settings of recovery modeling, but the Road Network Demo is incompatible. In that case, the plugin should return a clear error message instead of crashing.
I'm also adding the possibility to load the new csv outputs of infrastructure risk assessment as tables.
=> Catch exception in case of incompatible damage states for recovery modeling

svir/dialogs/viewer_dock.py, svir/metadata.txt
Companion of https://github.com/gem/oq-engine/pull/9016
Addressing https://github.com/gem/oq-engine/issues/8971
Before the addition of the AEP and OEP curves, the plugin displayed multiple curves, one per each realization or statistic selected with a multi-select widget.
Now that also AEP and OEP curves are available, I've added a selector allowing to pick either `loss`, `loss_aep` or `loss_oep` and to display the corresponding curve for each of the realizations or statistics selected. The label for this selector is `Exceedance Probability`, but perhaps another better name could be given instead.
We may want to display AEP and OEP curves together instead of realizations/statistics. Or we may even want to display everything together (all realizations/statistics and all ep/aep/oep) in a …
=> Adding OEP and AEP for event-based risk and damage calculations

svir/dialogs/load_output_as_layer_dialog.py, svir/metadata.txt
Fixes https://github.com/gem/oq-irmt-qgis/issues/206
I am doing it when creating layers of any kind, because the extent is always a rectangle and, even if in the properties it is displayed as empty, the object actually contains the coordinates. Therefore we can just increase the rectangle by a small delta.
With this fix, the plugin automatically (and correctly) zooms to layer also when loading a layer with only one point.
What we obtain is something more usable than before, although we introduce a little inconsistency, because we are declaring that the extent of our layer is bigger than its actual extent (that in fact is just a point). I believe the benefits justify the little inconsistency.
=> Increase the extent of layers having an empty extent in order to allow zooming to layer

svir/test/integration/test_drive_oq_engine.py
This should avoid the following:
https://github.com/gem/oq-irmt-qgis/actions/runs/6387469847/job/17335848919#step:6:1546
See https://github.com/gem/oq-irmt-qgis/pull/843 about the broken unit test with QGIS LATEST.
=> Do not force min_mag=6.5 when loading ruptures in tests

svir/metadata.txt, svir/tasks/download_oq_output_task.py, svir/tasks/extract_npz_task.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/840
The stacktrace was misleading. Actually the plugin was unable to load hcurves from the npz successfully downloaded through the engine API, because numpy.load complained about max_header_size being too small for that specific calculation.
Raising that parameter default by 10 times, it should be sufficient in our use cases.
@alejocaldeGEM I've just tried also with the Croatia use case, successfully.
This change needs to be backported to 3.16 and 3.17.
=> While extracting npz in numpy.load use max_header_size=100000 to fix e.g. some hcurves

svir/calculations/aggregate_loss_by_zone.py
For some reason, it looks like the algorithm SpatialJoinSummary suddenly disappeared from QGIS processing algorithms, therefore we have a broken unit test when running tests with the latest QGIS docker image.
I've written to the QGIS developers mailing list asking about this, to understand if the algorithm was recently replaced by something else or if it was perhaps deleted accidentally.
The additional check introduced by this PR should produce a clearer error message than https://github.com/gem/oq-irmt-qgis/actions/runs/6394447410/job/17356510404?pr=842#step:5:183
=> Add a check raising an error if qgis:joinbylocationsummary was not retrieved correctly

svir/calculations/aggregate_loss_by_zone.py
Addresses part of https://github.com/gem/oq-irmt-qgis/issues/844
Use hardcoded lists of predicates and summaries when runnign the algorithm qgis:joinbylocationsummary, because those lists are no more available after the porting of the algorithm from python to c++.
=> Use qgis:joinbylocationsummary in a way that works both on the python and c++ versions of the algorithm

.github/workflows/qgis_383.yml, .github/workflows/qgis_latest.yml, .github/workflows/qgis_ltr.yml
This should avoid failures like https://github.com/gem/oq-irmt-qgis/actions/runs/6502845711/job/17662478860#step:4:400
=> When running tests, wait that the webui becomes available before proceeding

svir/dialogs/load_avg_losses_rlzs_as_layer_dialog.py, svir/dialogs/load_damages_rlzs_as_layer_dialog.py, svir/dialogs/load_hcurves_as_layer_dialog.py, svir/dialogs/load_hmaps_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/load_uhs_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt
Addresses part of https://github.com/gem/oq-irmt-qgis/issues/839
Especially in the case with `collect_rlzs=true` it is pointless to display individual realizations. In case only one realization is available, it still makes sense to consider it as the mean.
=> When only one realization is extracted from the engine, it is displayed as the 'mean'

.github/workflows/qgis_ltr_engine_releases.yml, .github/workflows/test.yml
3.22 is the version of qgis-server we are currently using with the Geoviewer.
3.34 and 3.36 are the current ltr and latest, but using qgis/qgis:ltr and qgis/qgis:latest does not seem to work properly at the moment.
=> Test with qgis versions 3.22, 3.34 and 3.36

svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/dialogs/load_ruptures_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt, svir/utilities/utils.py
* Fixed the loader for ruptures
* Different way to select the event and the GMPE in oq-engine scenario calculations
* Fixed the header of aggregated average losses realizations in case of oq-engine parameter collect_rlzs=True
* Fixed a deprecation warning
=> Backport to master the recent fixes made for 3.19

.github/workflows/qgis_ltr_engine_releases.yml, .github/workflows/test.yml, svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/test/integration/test_drive_oq_engine.py, svir/test/unit/test_irmt.py, svir/test/unit/test_metadata_utilities.py, svir/test/unit/test_translations.py
Tests running on qgis 3.22, 3.34 (ltr) and 3.36 (stable) for python 3.9, 3.10 and 3.11 are green: https://github.com/gem/oq-irmt-qgis/actions/runs/9017144804
Tests checking compatibility between corresponding releases of the plugin and of the engine still have a couple of failures to be fixed in a separate PR: https://github.com/gem/oq-irmt-qgis/actions/runs/9017667633/job/24776590661#step:7:1588
=> Test on qgis ltr and latest using Xvfb

.github/workflows/qgis_ltr_engine_releases.yml, .github/workflows/test.yml
On qgis 3.22 the segfault sometimes happens, sometimes it does not. I prefer to keep it disabled for now.
=> Temporarily remove tests for qgis 3.22

svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/metadata.txt
Companion of https://github.com/gem/oq-engine/pull/9915
=> When loading gmfs, include secondary perils (if available) to the imt selector

svir/dialogs/drive_oq_engine_server_dialog.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/865
- The selection/deselection of a row is triggered by clicking on it
- If the user resizes columns, the new size is kept when refreshing the list
=> Improve the usability of the oq-engine calculations list widget

svir/dialogs/load_gmf_data_as_layer_dialog.py, svir/metadata.txt
Addresses https://github.com/gem/oq-irmt-qgis/issues/864 (please @alejocaldeGEM and @CatalinaYepes check if this implementation is enough, in particular for what concerns the generated attribute table).
=> Change the loader for GMFs, to pick the rlz first, then the event id, then the IMT

svir/dialogs/load_damages_rlzs_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py
It would be important to know since which version of the engine the convention `losstype_dmgstate` changed to `losstype-dmgstate`, and backport this fix to all versions that need this change.
=> Fix zonal aggregation for damages_rlzs and automatically create special indices

svir/dialogs/load_avg_losses_as_layer_dialog.py, svir/dialogs/load_damages_as_layer_dialog.py, svir/dialogs/load_output_as_layer_dialog.py, svir/dialogs/viewer_dock.py, svir/metadata.txt
I've also uniformed some display names of output types visualized in the Data Viewer, to the same names used in the engine.
(NOTE: based on https://github.com/gem/oq-irmt-qgis/pull/887)
=> When loading damages-rlzs or damages-stats, make it possible to select damage or consequences

svir/metadata.txt, svir/utilities/utils.py
Fixes https://github.com/gem/oq-irmt-qgis/issues/836
When QGIS loads data from CSV, if a field contains only 0 or 1 values, its type is automatically set as boolean. When loading data from the engine, we prefer the type to be integer instead. In order to achieve that, I need to replace the automatically created boolean fields with new integer fields, casting the boolean values to int.
The tricky part I did not expect is that the layer data provider used by QGIS to manage csv-based layers does not allow adding new fields in the usual way (it fails silently while attempting to do so), so I had to perform an additional step, copying the csv-based layer into a memory layer that allows managing new features as I needed. I also had to be careful keeping the original order of the fields.
=> Prevent integer fields from being cast to booleans by QGIS when they contain only 0 or 1 values, while loading from CSV
